### ISSUE TITLE
中文翻译内容推送申请

### ISSUE THREAD

**Issue by ShenQingchuan** [vuejs-translations/docs-zh-cn#1]
我的仓库是 https://github.com/ShenQingchuan/vue-docs-new-cn
预览地址是：https://vue-new-docs-cn.netlify.app

实时跟进这 vuejs/docs : next 的翻译状态

@yyx990803
- [x] 我是否可以加入这个 org 推送 翻译内容 及其他代码 呢？**DONE**

等待初次审阅完成后，我们再决定推送策略。

**Comment by ShenQingchuan** [comment]
翻译进度 tracked in this issue：

https://github.com/ShenQingchuan/vue-docs-new-cn/issues/2

**Comment by ShenQingchuan** [comment]
Closed by https://github.com/orgs/vuejs-translations/teams/zh-cn/discussions/1

**Comment by Jinjiang** [comment]
Hi @ShenQingchuan 我会邀请目前 vuejs 中文文档的维护者加入这个项目未来一起维护和持续翻译，谢谢🙏
