### ISSUE TITLE
https://cn.vuejs.org/ 国内访问需要使用vpn 不使用vpn的时候访问不到

### ISSUE THREAD

**Issue by yuanzengding-1234** [vuejs-translations/docs-zh-cn#1014]
![image](https://github.com/user-attachments/assets/488bf066-afc9-4d29-85d8-14b194bb5e6e)

**Comment by veaba** [comment]
按照下面的备份站点临时访问下

https://github.com/vuejs-translations/docs-zh-cn/issues/984#issuecomment-2288080548

这个问题，继续跟进 #984

**Comment by ikxin** [comment]
@yuanzengding-1234 Vue.js 中文文档使用的是 Cloudflare CDN，偶尔（绝大多数时候能正常访问）对大陆环境不是特别友好，我测试了一下 #984 中提到的几个备用站点，主站点访问正常，Netlify 移动节点无法访问，Vercel 和 CloudFlare 均无法访问。

为了解决中国大陆特殊的网络环境问题，我在半年前计划发起一个中文文档翻译和镜像的项目，并通过了漫长的工商注册以及 ICP 备案、公安备案等相关手续，其中就包括了 Vue、Vite 等中文文档的镜像服务，均采用大陆服务器以及大陆 CDN 进行加速访问。

一些镜像的站点：

- Vue 中文文档镜像：https://vue.zhcndoc.com
- Vite 中文文档镜像：https://vite.zhcndoc.com

一些翻译和维护的站点：

- Nuxt 非官方中文文档：https://nuxt.zhcndoc.com
- UnoCSS 非官方中文文档：https://unocss.zhcndoc.com
- VueUse 非官方中文文档：https://vueuse.zhcndoc.com

因考虑到合法合规以及文档内容版权等问题，我未曾公开宣传过该项目，但最近在参与 Vue.js 中文文档的翻译工作，偶然间看到这个 issue，我觉得或许能够帮助到一些无法访问官方中文文档的朋友，这应该是我的一次在 Github 提起该项目。我不确定该项目是否会对官方中文文档造成侵权行为，如果有不妥的地方，欢迎提出指正。

以下是上述站点的测速结果：

| 域名                                | 测速结果                                                                             |
| ----------------------------------- | ------------------------------------------------------------------------------------ |
| https://cn.vuejs.org/               | ![](https://github.com/user-attachments/assets/b717ea83-1913-4ec4-99f7-741898b4c6c2) |
| https://vue-docs-zh-cn.netlify.app/ | ![](https://github.com/user-attachments/assets/5b9dace8-a950-4362-8411-443cc02e5fcd) |
| https://vue-docs-zh-cn.vercel.app/  | ![](https://github.com/user-attachments/assets/87d11090-38e8-47de-bb34-7a0ff981e9af) |
| https://cn-staging.vuejs.org/       | ![](https://github.com/user-attachments/assets/03cda081-d505-4499-82aa-179d90f2ac34) |
| https://vue.zhcndoc.com/            | ![](https://github.com/user-attachments/assets/7487671f-c087-4c90-b3ec-2636890f3c18) |

**Comment by yuanzengding-1234** [comment]
谢谢解答，我最近使用镜像网站访问vue文档
