### ISSUE TITLE
新增翻译约定讨论

### ISSUE THREAD

**Issue by Justineo** [vuejs-translations/docs-zh-cn#1016]
* suppress

  候选：消除 / ~抑制~ / 阻止

  我在 #1005 暂时翻译为了“消除”，见 https://github.com/vuejs-translations/docs-zh-cn/pull/1005#discussion_r1751167918

* shadow root

  候选：保留原文 / 影子根

  我在 #1013 暂时保留了原文，见 https://github.com/vuejs-translations/docs-zh-cn/pull/1013#discussion_r1756308801

有结论后更新到 wiki。

**Comment by KiritaniAyaka** [comment]
文档中 suppress 只用于「警告」这一对象，译为「抑制」感觉搭配不太合适，「消除」则很好，但个人更偏好译为「阻止」。相较「消除警告」，感觉「阻止警告」可以暗示读者问题本身并没有解决，只是警告被阻止发出了。

至于 shadow 个人认为译为「影子」比较合适，MDN 也使用了这个翻译，说明这个翻译已经有一定受众。其次，作为专有名词的翻译，最好是可以体现出事物本身的性质和背景，而「影子」可以让国人联想到「影子系统」进而提示其与宿主文档的隔离性。

**Comment by Jinjiang** [comment]
https://www.chinaw3c.org/archives/1109/
这是我找到的 W3C China 的译法：“影子 DOM”，2015 年

**Comment by Jinjiang** [comment]
suppress 我觉得不必当作专有词汇来看待，只要信息传递到位且通顺就行，我个人也觉得“阻止”更通顺一些

**Comment by Justineo** [comment]
Ps. 如果用“影子根”的话，文档中的 Shadow DOM 也需要统一更新为“影子 DOM”。

**Comment by Jinjiang** [comment]
和 @Justineo 快速讨论了一下，suppress 不放入术语约定，根据实际语境酌情翻译即可，shadow 统一翻译为影子。Wiki 已更新。
