### ISSUE TITLE
页面未找到 你打开了一个不存在的链接：/api/built-in-special-elements.html。 不介意的话请提交到这里，我们会跟进修复。

### ISSUE THREAD

**Issue by 21wulixiaoxuan12112** [vuejs-translations/docs-zh-cn#1052]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

在搜索框输入<template>查询后得到：页面未找到
你打开了一个不存在的链接：/api/built-in-special-elements.html。
不介意的话请提交到这里，我们会跟进修复。

**Comment by KiritaniAyaka** [comment]
强制刷新一下，应该是缓存导致的

**Comment by 21wulixiaoxuan12112** [comment]
强制刷新后可以找到了，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月5日(周四) 凌晨0:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vuejs-translations/docs-zh-cn] 页面未找到 你打开了一个不存在的链接：/api/built-in-special-elements.html。 不介意的话请提交到这里，我们会跟进修复。 (Issue #1052)




 
强制刷新一下，应该是缓存导致的
