### ISSUE TITLE
[认领][已翻译未校对]: src/guide/components/props.md

### ISSUE THREAD

**Issue by watonyweng** [vuejs-translations/docs-zh-cn#107]
[card-75930834](https://github.com/vuejs-translations/docs-zh-cn/projects/1#card-75930834)

**Comment by JohnieXu** [comment]
@watonyweng @wxsms 请问这篇文章是已经认领校对了吗，还是处于待校对？

**Comment by wxsms** [comment]
目前由 @watonyweng 同学认领校对。
