### ISSUE TITLE
Composable 的译法讨论

### ISSUE THREAD

**Issue by Jinjiang** [vuejs-translations/docs-zh-cn#118]
讨论来源：https://github.com/vuejs-translations/docs-zh-cn/pull/81

个人觉得由两种备选译法：“组合式”和“可组合”，通常可默认跟一个“函数”
例如： What is a "Composable"? -> 什么是“组合式”函数/什么是“可组合”函数
看看大家的意见如何。

谢谢

**Comment by veaba** [comment]
投 “可组合”

**Comment by KimYangOfCat** [comment]
投 “组合式”，保持与 组合式 API 相同的风格

> “可组合函数”是一个利用组合式 API 来封装可重用**有状态逻辑**的函数。

**Comment by wxsms** [comment]
组合式+1

**Comment by AkaHanshan** [comment]
组合式，用来描述函数类型更为准确，而可组合更偏向于该函数的一种用法或者说特点

**Comment by initdc** [comment]
`可组合` +1


`组合式API`的 原词 `composition API`, 属于用名词修饰名词, 例如: 人民企业家

`option` 通常是一个 object, 是可选的, 短语: optional option
`composition` 通常是一个function, 是可组合的, 短语: composable composition

原文 `What is a "Composable"?` 有语病, 形容词 不加数量
更准确的语句应为: 
- `What is "Composition"?`
- `What is the meaning of "Composable"?` 
- `What does the "Composable" mean?` 
- `What is a "Composable" function?` 
- `What is a "Composition"?`

结合上下文, 本段章节标题 `Reusability`, 意为 `可重用性`, 下面应表其 `能力 functional` `特性 feature`,  而非 `属性 property`, 其`能力` `特性` 可由`属性`得以实现, 但`属性`仍非主语地位.

如译为: `组合式` , 确实有表 `特性`的含义, 但不如`可组合`直观, 
更因`组合式` 出处乃是 名词修饰名词, 我 `composable` 都带`able`的词尾了, 还不能表达我的`能力`? 我的`可`呢?

从 单词 组合来说:
`选项` 可以组词 `可选项`, `选项式`, `选项` 为主语
`组合` 可以组词 `可组合`, `组合式`, `组合` 为主语

从 单词 权利平等来说
我投 `可组合` 

(•̀ᴗ•́)و ̑̑
宝贝加油飞, 大哥永相随C

最后, 我觉得在推 Vue3 新版本, 表现 新特性 的关键时间节点, 涉及`Composition API`这个关键特性, 此事征求一下 尤大佬  的意见, 更合适.

**Comment by Jinjiang** [comment]
我一定程度上认同 what is composable 不算是标准的语法，但同时如果从纯语法的角度看 composition 也不是“组合式”，而就是“组合”。这也是我觉得翻译这件事情复杂的地方，一方面追求准确，另一方面追求通顺易懂。

考虑到这里大家在这里已经有各自不同的观点，并且有各自的理由，我倾向于多引入一些具体的例句来讨论。

> What is a "Composable"

> 
> In the context of Vue applications, a "composable" is a function that leverages Vue Composition API to encapsulate and reuse stateful logic.
>
> A composable can update its managed state over time.
>
> You can use the full range of Composition API functions in composables.
>
> The cooler part about composables though, is that you can also nest them: one composable function can call one or more other composable functions.
>
> Extracting Composables for Code Organization

更多例句可以在

https://vuejs.org/guide/scaling-up/testing.html#component-testing

和

https://vuejs.org/guide/reusability/composables.html

找到。

原则上：1) 无二义性，即不会产生歧义 2) 直观通顺易理解

在我看来就是好翻译。

谢谢

**Comment by SkyeYoung** [comment]
> In the context of Vue applications, a "composable" is a function that leverages Vue Composition API to encapsulate and reuse stateful logic.

从例句来看，似乎这里的 ”Composable“ 是指可组合的函数，也许应该把它当成名词来翻译，也就是可组合函数或者组合式函数。而上面提到的 “Composition API” 更类似”专有名词“（我不太清楚确切的名词），语法什么的大概无所谓。 : (

不过，虽然说起来挺顺口的，”组合式“这个词的确切意思是什么呢？个人目前的印象，这个词展开后就是”可组合的样子的“？

反正翻译的话，要完全对应原文或者符合原文的语法肯定是很难的，也许在句子通顺的情况下，只要把原本的意思清楚地表达给读者就可以了？（大家都知道是这个就 OK？）

**Comment by Yorksh1re** [comment]
可组合+1

**Comment by ShenQingchuan** [comment]
我个人是比较推荐 “可组合函数” 的。

从翻译角度上讲，这两个词都是可以的。

那么我们分别来罗列一下两个词的对比吧：

- 可组合：

Evan 的意见是 “组合式”
> Evan: 
> 个人偏组合式 —— From WeChat

**Comment by Jinjiang** [comment]
从目前的讨论来看倾向于“组合式”和“可组合”接近五五开吧 (没有算上最有一则是 4:5)，大家的理由也都充分阐述了。我结合大家的讨论也简单征求了一下 @yyx990803 本人的意见，觉得更偏向翻译为“组合式”。

我稍后会根据自己的理解校对一遍相关的译文，然后找大家 (包括 Evan) review，届时我们仍可以 case-by-case 讨论。

谢谢

**Comment by yuhaoboris** [comment]
我個人也傾向「組合式」
