### ISSUE TITLE
#110 的 PR 引起了 build 错误，后续构建都会影响，正在定位中

### ISSUE THREAD

**Issue by veaba** [vuejs-translations/docs-zh-cn#119]
初步判断是 引入了 md 中引入的组件文件引发，在定位具体的问题：

```md
<div class="options-api">
  <VueSchoolLink href="https://vueschool.io/lessons/conditional-rendering-in-vue-3" title="Free Vue.js Conditional Rendering Lesson"/>
</div>

<div class="composition-api">
  <VueSchoolLink href="https://vueschool.io/lessons/vue-fundamentals-capi-conditionals-in-vue" title="Free Vue.js Conditional Rendering Lesson"/>
</div>
```
![image](https://user-images.githubusercontent.com/8652596/155888714-ce8e4696-b5f9-4960-8aed-750a71456681.png)

详细报错，见 actions

@Justineo @Jinjiang

**Comment by veaba** [comment]
定位到 #110 PR 引入的变更中，没有引入 `VueSchoolLink` 组件引发的。

需要发起一个 PR 来修复改问题。

**Comment by KimYangOfCat** [comment]
最好将英文分支最新状态全部同步过来，目前本仓库的同步似乎依旧是人手工同步的，是否考虑引入一些自动化同步手段？
目前译者和校对者似乎也在承担着仓库具体文件的一些同步工作，我个人认为这会带来更多的冲突与工作量。

理想状态应该是这样的，自动化同步手段完全负责全部英文内容的同步，并集中解决所有翻译冲突，个人译者和校对者只关注译文的翻译和校对，这样能提升仓库的实时性以及编译的稳定性

**Comment by initdc** [comment]
## 流程建议:

使用 3 个 `branch` 来构建翻译体系

- `upstream`:  由 bot 自动同步的英文仓库主分支 
- `current`:  基于此分支进行 翻译工作，后续人工 `git cherry-pick` 一部分合并,  控制同步粒度，以控制更新翻译的工作量
- `main`:  翻译分支

**Comment by wxsms** [comment]
@KimYangOfCat @initdc 关于同步问题，我新开了一个 issue #121 ，请移步到那里讨论。谢谢。

**Comment by wxsms** [comment]
问题已由 #124 修复
