### ISSUE TITLE
关于特指报错信息的内容是否翻译的疑问

### ISSUE THREAD

**Issue by wxsms** [vuejs-translations/docs-zh-cn#12]
发现了几处。举例：

```ts
import { ref } from 'vue'

// inferred type: Ref<number>
const year = ref(2020)

// => TS Error: Type 'string' is not assignable to type 'number'.
year.value = '2020'
```

这里面 TS Error 一段是否应该翻译？我发现目前是被翻译为了 `TS 错误：类型 'string' 不可以赋值给 'number'`，但是根据我的理解这里不应该翻译，因为是特指 TS 的报错信息，应该原样输出，否则翻译后可能更为迷惑。不知道大家怎么看？

**Comment by KimYangOfCat** [comment]
我赞同不翻译，保持英文。对于老手， 这类信息翻译和不翻译的区别不大，基本都能看懂。但是对于新手，新手的思维逻辑却总是纠结在表象上，总是会疑惑为什么屏幕输出的信息和文档标注的信息不一样？
所以这类信息的翻译不仅不会有任何帮助，反而会造成新手的疑惑！

**Comment by Jinjiang** [comment]
我也觉得这里不翻译比较好，因为这个是要对照实际程序输出的结果的，翻译过后反而和实际结果对不上了

**Comment by Jinjiang** [comment]
鉴于这里已经长期没有更多讨论了，不介意的话我们就算是达成共识不翻译了。
谢谢

**Comment by Jinjiang** [comment]
https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5#3-%E5%85%B3%E4%BA%8E%E6%96%87%E6%A1%A3%E4%B8%AD%E7%9A%84%E4%BB%A3%E7%A0%81%E7%89%87%E6%AE%B5

相关结论已更新至 wiki
