### ISSUE TITLE
[认领][校对]: src/guide/components/slots.md

### ISSUE THREAD

**Issue by JohnieXu** [vuejs-translations/docs-zh-cn#127]
认领校对`src/guide/components/slots.md`

**Comment by JohnieXu** [comment]
已校对完成，见PR #135

**Comment by cucuzi** [comment]
插槽内容与插口那里，FancyButotn是不是拼错了
![image](https://user-images.githubusercontent.com/48954949/162115514-b281aeab-76dc-4155-95a3-93a87fc3c84d.png)

**Comment by wxsms** [comment]
> 插槽内容与插口那里，FancyButotn是不是拼错了 ![image](https://user-images.githubusercontent.com/48954949/162115514-b281aeab-76dc-4155-95a3-93a87fc3c84d.png)

fixed https://github.com/vuejs-translations/docs-zh-cn/commit/705788a6e949f869732f8811c19169e44d0bb3e0 ，欢迎使用页面上的 edit this page功能直接发起PR @cucuzi
