### ISSUE TITLE
wrap/unwrap 译法讨论

### ISSUE THREAD

**Issue by Jinjiang** [vuejs-translations/docs-zh-cn#133]
目前已有的提议：

1. 包裹/解包 (之前中文文档讨论的结论 https://github.com/vuejs/docs-next-zh-cn/issues/487)
2. 包装/解包
3. 包裹/解套
4. 引用/解引用

更多之前的讨论来自：#2

期待大家的意见和看法，谢谢

**Comment by wangyan666** [comment]
1或2，解包很令人熟悉。

**Comment by KimYangOfCat** [comment]
支持 2

**Comment by Matrix53** [comment]
感觉包装/解包比较好，包裹这个词感觉不经常用作动词

**Comment by Jinjiang** [comment]
那我们就约定到 2 包装/解包 了，稍后我来统一更新
谢谢
