### ISSUE TITLE
关于特指 css 的 class/style 是否翻译的问题

### ISSUE THREAD

**Issue by wxsms** [vuejs-translations/docs-zh-cn#149]
前情提要：#106 

大家如果觉得有必要建立共识的话，我们可以在这里继续讨论。谢谢。

cc @KimYangOfCat @veaba @Jinjiang

**Comment by Jinjiang** [comment]
补充一下我的建议 (一部分来自原贴)：

首先 Vue 不是一个纯粹讨论 CSS 的地方，所以至少标题我强烈建议保留英文，即“Class 与 Style 绑定”，理由很简单，一般读者看到左侧导航的时候会引起歧义：

![image](https://user-images.githubusercontent.com/206848/158002532-c3585cfb-e572-4ff0-8574-aca20d890cec.png)

至于文章内的翻译，如果没有特别的理由，我倾向于保留之前版本文档的翻译和阅读的习惯，即仅翻译非代码的 style 为“样式”，原因也很简单，有些用户是从 v2 或别的版本迁移过来的，我们希望尽量保留这个一致性。但这里即便把 class 翻译成类我觉得没有原则性问题，不像标题的问题那么明显。

谢谢

**Comment by SkyeYoung** [comment]
个人觉得，某一些专有名词，不翻译应该也没有关系。就像下面的 Ref 或者 CSS 这个词本身一样。

**Comment by wxsms** [comment]
赞同 @Jinjiang 的建议，标题保留英文，正文内翻译非代码的 style 为“样式”。至于正文中的 class 建议翻译为“类”。

**Comment by veaba** [comment]
个人看法，css 中的 class 与 JS 中的 class，不应该混淆。

CSS 中 class，保留更符合原意。

我理解 style 大家都叫习惯了，标题最好也是保持  style。
class 则标题保留，正文推荐保留原文，使用 `类` 也不是很必须。

同意 jinjiang 的说法。

**Comment by Jinjiang** [comment]
OK，那我们就达成共识了，即：

- 标题译为：“Class 与 Style 绑定”
- 正文的非代码 style 译为“样式”，class 不翻译

我稍后做更新

谢谢

**Comment by xfq** [comment]
class在CSS中除了用作class selector（选择HTML/SVG/MathML中与`class`属性值匹配的元素）之外，还在pseudo-class这个词中出现（如`:lang()`），这时是否可以译为“伪类”？

**Comment by wxsms** [comment]
> > class在CSS中除了用作class selector（选择HTML/SVG/MathML中与`class`属性值匹配的元素）之外，还在pseudo-class这个词中出现（如`:lang()`），这时是否可以译为“伪类”？
> 
> 原则上已经广泛约定俗成、不产生歧义、或作者本人认可的地方我觉得没有问题

如果这样的话，我觉得正文中的 class 是否翻译为“类”还有讨论空间。我是倾向翻译的。理由是：

1. CSS 类已经是一个常见概念了，这个“类”通常是与 CSS 一起出现的。造成混淆的概率应该不大；
2. CSS 伪类如果翻译的话，CSS 类不翻译就显得有些许不统一；
3. CSS 类的扩展名词的翻译，如类名、类选择器等，也较为常见；
