### ISSUE TITLE
建议wiki翻译须知中增加译文保持与原文行号一致

### ISSUE THREAD

**Issue by wxsms** [vuejs-translations/docs-zh-cn#16]
该规则已存在于 @ShenQingchuan 整理的[翻译说明](https://staging-cn.vuejs.org/about/translation.html#%E6%9B%B4%E6%96%B0%E5%86%85%E5%AE%B9%E5%90%8C%E6%AD%A5%E7%AD%96%E7%95%A5)章节中：

> 由于 Vue 文档以 Markdown 书写，每一行成一个自然段。因此在 Markdown 文档中原则上应该保证中英文行号一一对应，以保证后续更新时位置不发生错乱

但原文档团队并无此约定。我理解保持行号一致有许多好处：

1. 校对时可以快速定位原文
2. 可以以此为基础对接自动同步的 bot
3. 即使不进行自动同步，对手动同步的工作也有益处，能够帮助快速定位

对译者注的内容，可以在文末追加，或者在本行添加。这样仍然可以保证行号单向（原文->译文）一致。希望可以达成共识。谢谢。

**Comment by veaba** [comment]
保持原行，大多数情况都是一致的，可能存在某个特殊情况下才会出现。

我赞同尽量维持原行。

**Comment by Jinjiang** [comment]
其实绝大多数情况下我们不必刻意做什么应该就是同一行的，我个人经验有以下几种情况需要特殊关照：

1. 有单行的译者注
2. 有本地化的调整，比如删掉一些国内无法访问或不推荐访问的 banner 之类的，或中文区特别的赞助商或赞助活动
3. 代码注释的英文描述会因为超过 80 个字符而折行，翻译成中文之后行数有的时候会不一样

我暂时对目前保持更新的具体操作机制不够了解，所以不确定这几种情况是否可以有可行的对策，如果没有的话我倾向于做一些针对性的讨论。

谢谢

**Comment by Jinjiang** [comment]
以更新到 wiki
谢谢大家
