### ISSUE TITLE
术语词典与专有名词译法的需求

### ISSUE THREAD

**Issue by SkyeYoung** [vuejs-translations/docs-zh-cn#162]
# Question 1
是否可以在本仓库创建一个单独的 Wiki 记录一些计算机通用或 Vue 中常用的、普遍认同的术语呢？

## Description
我发现我认领的 src/guide/scaling-up/testing.md 中已经使用了“可组合函数”作为 “Composable” 的翻译，而实际上，这个翻译还在 https://github.com/vuejs-translations/docs-zh-cn/issues/118 中讨论。

另外，某一些多义的翻译是否可以有一个更统一的译法呢？（突然把例子忘掉了……）

其他有讨论结果的翻译也是，尽管后来者可以翻 Issue，但如果有一个页面进行了系统的整理，是不是会更方便一些呢？

# Question 2
某一些用到的名词，如端到端（E2E）、插槽（slot）等等，我觉得可能不翻译更好，这部分的内容是否有一些翻译上的指导呢？我觉得如果有文字记录的翻译建议，可能能减轻一些后续的工作量？

**Comment by wxsms** [comment]
question1，我们是有一份术语表的，请见：https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5

question2，这种情况，如果没有在术语表中记录的，欢迎发起 issue 讨论，讨论后的结果将更新至 wiki。

谢谢。

**Comment by SkyeYoung** [comment]
> 我们是有一份术语表的

抱歉，才发现在 README 中有 wiki 的链接。

不知道到为啥，导航里没有，我一般都是往导航里找的：

![image](https://user-images.githubusercontent.com/48400568/158015977-30161ad0-8fc0-4597-9059-06e4685e568e.png)

只有进去以后才会显示：

![image](https://user-images.githubusercontent.com/48400568/158016058-c254218b-4b00-40f7-9c7b-5c103a3ec527.png)
