### ISSUE TITLE
关于 shorthand 译法讨论

### ISSUE THREAD

**Issue by Yorksh1re** [vuejs-translations/docs-zh-cn#167]
我在 Review [template-syntax.html#attribute-bindings](https://staging-cn.vuejs.org/guide/essentials/template-syntax.html#attribute-bindings)章节时，发现 `shortened` 一词被译为 `缩写`，同样的，[Vue 2 模板语法章节](https://cn.vuejs.org/v2/guide/syntax.html#%E7%BC%A9%E5%86%99)也是如此。个人在求证 [MDN](https://developer.mozilla.org/zh-CN/docs/Web/CSS/Shorthand_properties) 及其他文档的翻译工作[^1]时发现，`shortened` 一词基本被翻译成`简写`。

来自[wiki](https://zh.wikipedia.org/wiki/%E7%B8%AE%E5%AF%AB)：
>缩写有几种常见的形式：1. 截取词的首字母来代表这个词，如 C 代表 carbōnium（碳）；2. 截取词的前几个字母，如 Eng. 代表 England（英格兰）或 English（英语）；3. 分别截取一个词的两个部分的第一个字母，如 cm 代表 centimeter（厘米），TV 代表 television（电视）；4. 截取词的首字母和最后一个字母，如 No. 或 [№](https://zh.wikipedia.org/wiki/%E2%84%96) 代表 numerō（号数）；5. 截取词组中每个主要单词的第一个字母，如 UN 代表 the United Nations（联合国）

例如：
> “GNU”是“GNU's Not Unix!”（GNU并非Unix！）的首字母递归缩写。
> World Trade Organization → WTO

而 `v-bind` 缩写为 `:`，或 `v-on` 缩写为 `@` 等，不符合`缩写`一词的定义，个人更建议译为`简写`。

我觉得有必要讨论一下要不要翻译成简写？

[^1]: [Angular](https://angular.cn/guide/structural-directives#shorthand)、[React](https://zh-hans.reactjs.org/docs/react-api.html#reactfragment)、[Svelte](https://www.sveltejs.cn/docs#bind_element_property)等。

**Comment by Yorksh1re** [comment]
CC @Jinjiang @wxsms

**Comment by wxsms** [comment]
有理有据，我同意翻译为“简写”。

**Comment by Jinjiang** [comment]
赞，我也同意改成“简写”
