### ISSUE TITLE
[认领][翻译]: src/guide/extras/custom-renderer.md

### ISSUE THREAD

**Issue by Yorksh1re** [vuejs-translations/docs-zh-cn#173]
![image](https://user-images.githubusercontent.com/70258597/158046589-4aecf630-6b49-4098-a986-872e6efc3bc0.png)

捉个小虫：更正 custom-renderder 为 custom-renderer

**Comment by wxsms** [comment]
发现这篇文章目前好像是空白的，我把这个卡片去掉吧。谢谢。不介意的话我就关闭该认领了。
