### ISSUE TITLE
认领翻译 src/api/application.md

### ISSUE THREAD

**Issue by Sh1-5** [vuejs-translations/docs-zh-cn#175]

**Comment by wxsms** [comment]
参考 #8 

> 注意：通常我们只处理英文版中已经稳定的页面，目前已经稳定的部分只有 src/guide 目录下的页面，英文版的文档也在集中撰写中，后续会陆续增加稳定的页面

目前不建议翻译 api 下的文档。

**Comment by Sh1-5** [comment]
好的
