### ISSUE TITLE
正式上线前可能要将首页视频替换为国内源

### ISSUE THREAD

**Issue by wxsms** [vuejs-translations/docs-zh-cn#177]
RT，毕竟这个是最明显的按钮。

![1647224764](https://user-images.githubusercontent.com/5960988/158094386-b819b7ee-14e0-4abd-8cee-4471a428edbb.jpg)
![1647224764(1)](https://user-images.githubusercontent.com/5960988/158094398-f4a5ed8a-4d9c-4034-a4cd-ff9b931e0f83.jpg)

**Comment by Justineo** [comment]
这个好像还缺一个字幕，之前 Vue 2 的官网上那个是有中文字幕的。部署之前是优酷赞助的。

**Comment by Jinjiang** [comment]
我们把 v2 的代码搬过来用吧

**Comment by KimYangOfCat** [comment]
本次国内这个也决定了使用优酷嘛？可不可以考虑使用小破站（bilibili.com）？个人感觉小破站的氛围更适合开源项目。

**Comment by Jinjiang** [comment]
关于优酷的选用 (包括没有选择 B 站) 之前讨论过，感兴趣的可以看这里：
https://github.com/vuejs/cn.vuejs.org/issues/729#issuecomment-386999657

**Comment by KimYangOfCat** [comment]
@Jinjiang 嗯嗯，看过了，不过讨论的时间已经是4年前了，以 B 站如今的发展状态，4年前所列举的缺点似乎都已不存在了。评论以及弹幕等功能都能关闭了。so，我认为还是可以重新考虑一下 B 站，毕竟 B 站上编程相关的内容和用户更多，对于 Vue 生态来说，应该是一件好事儿。仅个人建议，还是看 Vue 官方团队的意见吧

**Comment by Jinjiang** [comment]
@KimYangOfCat 我个人保持开放态度，但实际功能和实现层面还是有不少细节的。不然这样，如果你有兴趣的话，可以简单做个版本，方便我们进一步讨论和评估，你看如何？

**Comment by Jinjiang** [comment]
经过团队小范围讨论，决定暂时把首页的视频下掉，稍后我会发起一个 PR，谢谢
