### ISSUE TITLE
简介中的单文件组件项不受选项式/组合式开关影响

### ISSUE THREAD

**Issue by Seidko** [vuejs-translations/docs-zh-cn#183]
简介一文中“单文件组件”段落不受 选项式/组合式 开关的影响

如图：
![image](https://user-images.githubusercontent.com/64234553/158109843-84054cf7-e5a9-4a05-9ed7-5738c68f4678.png)

**Comment by JohnieXu** [comment]
@Seidko 对比了一下，英文官网这里也不受 选项式/组合式 开关的影响；同时也看了下英文项目代码和当前项目一致，如下，也是不受 选项式/组合式 开关影响

```vue
<script>
export default {
  data() {
    return {
      count: 0
    }
  }
}
</script>

<template>
  <button @click="count++">Count is: {{ count }}</button>
</template>

<style scoped>
button {
  font-weight: bold;
}
</style>
```

https://github.com/vuejs/docs/blob/main/src/guide/introduction.md#single-file-components

**Comment by Seidko** [comment]
好的，那我去英文站发，感谢

**Comment by KimYangOfCat** [comment]
@Seidko 
这并不是BUG，而是简介中的代码故意不实现切换功能。API风格切换功能主要正对 Vue 中两种风格都支持的功能特性进行解释说明时才用的。而简介只是一个Vue功能信息的一个极简缩影。
你可以理解为，在简介中正式介绍了 选项式API 和组合式API 之后，后续的内容才有两种风格可选。所以简介中不实现风格切换，就是为了先介绍这两种风格。

**Comment by Seidko** [comment]
@KimYangOfCat 原来如此，感谢！
