### ISSUE TITLE
vue解构插槽scoped-slots下的工作原理翻译个人建议

### ISSUE THREAD

**Issue by shiwanjun1995** [vuejs-translations/docs-zh-cn#197]
English：https://vuejs.org/guide/components/slots.html#scoped-slots 
**You can think of a scoped slot as a function being passed into the child component. The child component then calls it and passing props as arguments:**
Chinese：https://v3.cn.vuejs.org/guide/component-slots.html#%E8%A7%A3%E6%9E%84%E6%8F%92%E6%A7%BD-prop
**作用域插槽的内部工作原理是将你的插槽内容包括在一个传入单个参数的函数里：**
本着我大中国中文简洁明了、博大精深的精髓，我感觉这块翻译成这样会不会更好？
**作用域插槽的内部工作原理是将你的插槽内容放到一个传入了单个参数的函数里：**

**Comment by veaba** [comment]
欢迎发起 PR 来更正。

**Comment by KimYangOfCat** [comment]
感觉区别不是很大，不过欢迎PR

**Comment by Jinjiang** [comment]
如果这里没有更多后续讨论我就先关闭了，同时欢迎随时 PR
谢谢
