### ISSUE TITLE
自定义组件v-model不更新父组件数据

### ISSUE THREAD

**Issue by mooshine520** [vuejs-translations/docs-zh-cn#205]
![image](https://user-images.githubusercontent.com/36201730/159239284-b65caeea-132e-40a1-8e91-39200b90c85a.png)
![image](https://user-images.githubusercontent.com/36201730/159239355-e058d14c-0d11-4889-be04-9955e9ccc134.png)
![image](https://user-images.githubusercontent.com/36201730/159239540-6fd09ff6-2109-4617-ab0f-495a9552f832.png)
用setup语法糖标签写的代码
v-model对应的ntab值不变化，需要在@update:modelValue中手动进行值的更新

**Comment by KimYangOfCat** [comment]
本仓库并不讨论开发相关的问题，只讨论官方文档中文翻译相关的问题。
建议你去[官方论坛的中文板块](https://forum.vuejs.org/c/chinese/7)发布问题讨论
