### ISSUE TITLE
响应式基础模块下中文官网的例子和英文官网不同，且例子本身有误

### ISSUE THREAD

**Issue by Aimer-Fan** [vuejs-translations/docs-zh-cn#207]
在 组合式API风格 -> 基础 -> 响应式基础 -> ref 在模板中的解包中的【下面的表达式将不会像预期的那样工作：】给出的示例代码有误：

英文版为
`{{ object.foo + 1 }}`
中文版为
`{{ object.foo }} <!-- 无法自动解包 -->`

中文版给出的示例是错误的，`{{ object.foo }}` 不会被解析为 `[object Object]`。

**Comment by wxsms** [comment]
这个问题应该已经在 #201 中修复了。

**Comment by Aimer-Fan** [comment]
好的，感谢
