### ISSUE TITLE
[认领][翻译]: src/api/sfc-script-setup.md

### ISSUE THREAD

**Issue by wangrongding** [vuejs-translations/docs-zh-cn#214]
[认领][翻译]: src/api/sfc-script-setup.md  

我已翻译好。

**Comment by wxsms** [comment]
感谢贡献，不过参考置顶 issue：

> 注意：通常我们只处理英文版中已经稳定的页面，目前已经稳定的部分只有 src/guide 目录下的页面，英文版的文档也在集中撰写中，后续会陆续增加稳定的页面

当然，既然你已完成翻译，我们可以先保持这个 PR open，后续我们开始集中翻译 api 文档的时候再对你的工作进行 review。谢谢。（下次开始工作时建议提前认领，以避免出现类似情况）
