### ISSUE TITLE
guide/introduction.md 中关于 Vue 2 中文文档网址错误

### ISSUE THREAD

**Issue by cunyu1943** [vuejs-translations/docs-zh-cn#217]
如题，Vue 2 中文文档网址是：[https://cn.vuejs.org/](https://cn.vuejs.org/)，而不是 [https://v2.cn.vuejs.org/](https://v2.cn.vuejs.org/)，后者将跳转错误

**Comment by wxsms** [comment]
@yyx990803 Hello Evan, shall we apply the https://v2.cn.vuejs.org/ domain to v2 doc? seems it's not available for now.

**Comment by Jinjiang** [comment]
现在这一版文档还没有发布，发布之后 v2 的网址应该会是 v2.cn.vuejs.org。暂时没有线上更新的必要。
正式发布前夕我们会把所有发布相关的工作整理在一起处理。
