### ISSUE TITLE
[认领] [已翻译未校对]: src/guide/essentials/computed.md

### ISSUE THREAD

**Issue by KimYangOfCat** [vuejs-translations/docs-zh-cn#23]
认领 [card-75930975](https://github.com/vuejs-translations/docs-zh-cn/projects/1#card-75930975)

**Comment by KimYangOfCat** [comment]
已提交 #22

**Comment by Jinjiang** [comment]
@KimYangOfCat 感谢认领和贡献，我留意到你在记录文件路径和一些表示并列关系的场景下使用的是反斜线 (\)，一般情况下我们对于这个字符的使用场景是转义字符，或 Windows only 的文件路径。这里更普遍使用的字符应该是斜线 (/)。不介意的话后续可以尝试使用，方便大家理解和交流。

谢谢🙏

**Comment by KimYangOfCat** [comment]
@Jinjiang  这是我直接从windows文件管理器中复制相对文件路径后而忘记修改的小细节，抱歉，下次会注意哒

**Comment by wxsms** [comment]
既然 PR 已合并，我这里就关闭该 issue 了，感谢贡献。
