### ISSUE TITLE
vue3默认版本一个月了,中文版还没有出来?

### ISSUE THREAD

**Issue by github-ZH-cn** [vuejs-translations/docs-zh-cn#230]
vue默认版本将近两个月了,中文版还没有出来?翻译工作能不能搞快一点

**Comment by Justineo** [comment]
你可以通过捐助、提交 PR 等各种方式来加速。如果你什么都做不了，那么只能抱歉了。

**Comment by KimYangOfCat** [comment]
@github-ZH-cn  ？？？？
you can you up, no can no BB !

**Comment by github-ZH-cn** [comment]
技术菜问问不行吗,你们什么时候时候才能出来中文版啊?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vuejs-translations/docs-zh-cn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月2日(星期六) 中午1:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vuejs-translations/docs-zh-cn] vue3默认版本一个月了,中文版还没有出来? (Issue #230)





 
@github-ZH-cn  ？？？？
 you can you up, no can no BB !

**Comment by wangrongding** [comment]
> 技术菜问问不行吗,你们什么时候时候才能出来中文版啊?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "vuejs-translations/docs-zh-cn" ***@***.***&gt;; 发送时间:&nbsp;2022年4月2日(星期六) 中午1:26 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [vuejs-translations/docs-zh-cn] vue3默认版本一个月了,中文版还没有出来? (Issue #230) @github-ZH-cn ？？？？ you can you up, no can no BB ! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

工作量很大的，你也可以参与进来帮助一起加速完成~

**Comment by Justineo** [comment]
> 技术菜问问不行吗,你们什么时候时候才能出来中文版啊?

我们对技术水平没有偏见，但是如果态度不客气，那就没有回答你的必要了。
