### ISSUE TITLE
Git 历史以及工作流问题

### ISSUE THREAD

**Issue by MarvinXu** [vuejs-translations/docs-zh-cn#239]
首先，很高兴看到 [`Guide` 部分的翻译工作告一段落](https://github.com/vuejs-translations/docs-zh-cn/issues/8#issuecomment-1092861984)，恭喜大家！

事情是这样的，我看到在最新版的翻译中，我之前校对的那篇文章 [ssr.md](https://github.com/vuejs-translations/docs-zh-cn/blob/main/src/guide/scaling-up/ssr.md) 内容有所更新，出于对文字的负责和好奇，我就想从 Git 历史中看看修改的原因。

我打开我的[下一个 commit](https://github.com/vuejs-translations/docs-zh-cn/commit/2528fc79ecca3084d274f4c36ff5419c5099b19f#diff-82d5e630a635825e0b69c655029a62106351c3da36c75c65f729d121950cdebe)，但发现 diff 并不是基于我之前的修改。看到 commit message 为 `manual sync from English main.`，我猜可能是 merge 的时候解决冲突导致的。正是因此，我再看后面的 commit 已经没有意义了，因为它并不是基于我的修改。

个人认为目前同步英文文档的方式有几个问题：
- 两个 repo 的历史交错，导致很难看清关于中文文档的修改历史
- 解决冲突导致的历史记录篡改

eg 1:
<img width="322" alt="2022-04-09_122409" src="https://user-images.githubusercontent.com/7382357/162556478-61a0ff1c-aaba-48ff-9d1b-e9adfb30e6ac.png">

eg 2:
<img width="1280" alt="2022-04-09_121519" src="https://user-images.githubusercontent.com/7382357/162556110-b5839807-a12b-46ea-8a61-903caa6aa7e0.png">

eg 3:
尤大并没有提交这个 [commit](https://github.com/MarvinXu/docs-zh-cn/commit/83c8f6a25a5cb5fb333ae92e37c88f19917727a5) :sweat_smile:

不过想想要解决的话确实挺麻烦，要先知道当前翻译是基于英文文档的哪个版本，再拉取英文文档最新版本和当前版本的diff，基于英文的 diff 再去修改翻译…… 

先抛出问题吧，看看大家有什么好办法~

**Comment by MarvinXu** [comment]
> 总体上，**集中**翻译校对的时候实际情况相对比较复杂，因为同时有大量翻译/校对和原文更新产生，根据之前的经验这个是难免的。今后每次翻译和校对会逐步颗粒度放小，并且和英文版的同步率也会变高，问题就逐渐缓解了。

为什么非要以 merge commits 的方式来更新原文呢，既然还要逐行翻译和校对，不如直接在新的 commit 上更新。我觉得问题挺严重的吧，因为 merge 的操作不当导致别人的修改丢失，那在之前翻译和校对时的锱铢必较还有什么意义呢？我去调研一下有没有更好的方式。

**Comment by Jinjiang** [comment]
我可能没有完全理解你的问题，如果问题是英文更新和中文翻译过程中的冲突，那么是我之前的解释。如果问题特指 commit history 或相关的工作流程，可以先参考一下之前的关于工作流程的讨论 (比如 #121)。

另外，坦白说平时翻译和校对的时候我个人不太关注和依赖这部分，在不影响目前翻译质量和工作流程的基础上，我觉得可以探索和讨论一个更好的做法。

谢谢

**Comment by MarvinXu** [comment]
你理解的都对，就是两个问题

正如我在提问里描述的，
1. 起因：我的代码被合没了
2. 根本原因：工作流不可控

基于你的回答：
1. 无法避免
2. 已经在讨论

那我就关闭了。
