### ISSUE TITLE
关于其他和其它的选用问题

### ISSUE THREAD

**Issue by Jinjiang** [vuejs-translations/docs-zh-cn#24]
讨论源自 https://github.com/vuejs-translations/docs-zh-cn/pull/6#issuecomment-1013905760

目前我整理到的参考信息：

1. 目前已有的文档长期的译法如 @Justineo 所述
    > 前者 (其他) 指人，后者 (其它) 指物
2. 百度百科的描述：https://baike.baidu.com/item/%E5%85%B6%E5%AE%83/10940730
    > “其他”是标准用法，可以指代人和事物，建议日常使用及规范的书面文件使用；
    > “其它”是日常用法，一般只能指代事物；

我个人的倾向是保持现状，因为

1. 首先我相信两种译法都不太影响大家的阅读理解
2. 从务实的角度，如果要统一到“其他”，这些改动有可观的成本但没有特别明显的收益
3. 不算特别重要或明显，但个人觉得目前的译法因为能够区分出人和物可能还显得更精确一些

希望听到大家更多的意见

谢谢

**Comment by KimYangOfCat** [comment]
确实不影响理解，但这确实足够细节，不过我个人认为目前有必要统一到“其他”，在本文章也确实有可能出现这两种语景，一种是指代开发者（人），一种是指代其它工具（物）。像这样的细节不是每一位译者都会注意到的，且通常具体选用哪种翻译，往往取决于具体语境中的other指代的对象，做这样的分析选择对译者来说是极大的心智成本。再者，一旦句子结构复杂，译者就有可能分析错了 other 对象，导致混用两者（其他/其它）。后续维护者以及校对者想在这样的细节上纠正，往往是需要更大注意力，且此类混用通常不易被察觉。
综上所述，区分其他/其它从长远来看，只会消耗项目所有参与者的精力，既然“其他”即可指人又可指物，统一到“其他”，岂不是消灭了一个可能让所有项目参与者独立做选择的成本，节省了大家的精力放在更值得纠正的问题上。故我支持统一到“其他”，省时省力。
直接全局替换“其它”为“其他”，这并不需要费太多事儿，如果最终商议统一到“其他”，我愿意提交 PR 修复此问题。

**Comment by wxsms** [comment]
> 且通常具体选用哪种翻译，往往取决于具体语境中的other指代的对象，做这样的分析选择对译者来说是极大的心智成本

可能不至于“极大”，但确实存在一部分心智负担。不过如 Jinjiang 所说：

> 我相信两种译法都不太影响大家的阅读理解

也是事实。这里并没有一个非黑即白的标准，看了很多资料感觉总的来说两种用法都是可以接受的。既然如此，我的倾向是：**按照译者个人习惯来就 ok 了，只要不出现“其它”指人的情况，就应该都可以接受**。反正都不影响理解，感觉统一的价值确实不大。也许是属于“细节末节”一类的讨论了。

**Comment by Justineo** [comment]
考虑到协作的情况，我觉得可以接受全部统一到“其他”，全局搜索替换就能完成。

**Comment by Jinjiang** [comment]
那我们约定统一使用“其他”好了，稍后我更新到 wiki。
谢谢

**Comment by Jinjiang** [comment]
不好意思，我想再稍微多讨论一下，最近校对的时候遇到一个单复数并存的情况，就是 it 和 they 同时出现在一个句子里，依照上述结论，单数的 it 需要翻译成“它”，但复数的 they 则需要翻译成“他们”，从我自己的角度还是感觉比较奇怪的。不知道大家的感受或建议如何。

谢谢

**Comment by Jinjiang** [comment]
哦，是的，我当时被这个给搞混了……🤣

**Comment by awxiaoxian2020** [comment]
关于这个问题，我想作一些更“权威”的补充：

>《现代汉语异形词规范词典》明确指出，“其他”与“其它”是一组异形词，但“其他”能够包孕“其它”。至此，“其他”和“其它”的使用方式已经非常明显，“其他”可以代替“其它”行使语言表达作用，表达指代事物过程中仍然可以使用“其它”，表达指代人时必须使 用“其他”，由于“其他”能够包孕“其它”，为了语言规范，避免出现差错，在科技期刊编辑审校过程中使用“其他”为宜。
> 
> [1]王海波.科技期刊审校过程中异形词的使用辨析[J].通化师范学院学报,2021,42(12):124-128.DOI:10.13877/j.cnki.cn22-1284.2021.12.021.

![others](https://user-images.githubusercontent.com/69554233/219677644-abc37e29-d9da-4ecb-9f22-9e81e95548d2.png)
