### ISSUE TITLE
[认领][翻译]: src/api/render-function.md

### ISSUE THREAD

**Issue by pakchoily** [vuejs-translations/docs-zh-cn#240]

**Comment by changshou83** [comment]
🙋‍

**Comment by changshou83** [comment]
done

**Comment by pakchoily** [comment]
> done

不知道有没有理解错，你是完成src/api/render-function.md的翻译了吗？

**Comment by changshou83** [comment]
> 

是的

**Comment by changshou83** [comment]
哦哦，好吧，那是我理解错了，抱歉

**Comment by pakchoily** [comment]
> 哦哦，好吧，那是我理解错了，抱歉

没事呀，你可以看看我的pr #243  , 看看有什么问题可以直接改。可以帮忙校对下

**Comment by changshou83** [comment]
嗯，我感觉第97行可能有点问题，那里感觉应该是 指南 - 渲染函数 - 创建 VNode，我看英文文档的时候也是少了render function，个人觉得可能是尤大写的时候忘记加上了

**Comment by pakchoily** [comment]
是，应该是漏了。不过根据中文审核规范是不建议直接修改，需要以英文文档为准，有点打击你积极性。。。。
你可以去英文提个pr，解决这个问题。然后再回中文这里提交一次pr。

**Comment by changshou83** [comment]
感谢你的回复，我会去的。
