### ISSUE TITLE
关于 landmark 的译法

### ISSUE THREAD

**Issue by Jinjiang** [vuejs-translations/docs-zh-cn#25]
讨论源自 https://github.com/vuejs-translations/docs-zh-cn/pull/6#discussion_r785386288

目前我们的译法是“地标 (landmark)”，同时在之后加括号保留英文。
希望在此引入更多的讨论

谢谢

**Comment by KimYangOfCat** [comment]
嗯~，以后关于翻译讨论相关的内容具体到某词，可否给一些具体的语境？个人认为直接讨论某词如何翻译，就像不管语境，直接定某个单词的意思，十分困难，完全不知道怎么去讨论？

**Comment by wxsms** [comment]
@KimYangOfCat 参考此文：https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/landmark_role

我的建议是，这种非 vue 相关的 web 技术词汇，建议紧跟 MDN。我没有在 MDN 上面找到相关篇章有译文，因此建议不翻译。

**Comment by KimYangOfCat** [comment]
看完全文，我也赞同不翻译，暂时保持和MDN一致

**Comment by Jinjiang** [comment]
OK，那我们就选择不翻译了。之前出现 landmark 的地方我会统一处理一下
另外前端专业术语我觉得可以约定为优先参考 MDN 中文译法，如果没有中文译法则保留英文。如果大家没有异议稍后我更新到 wiki。

谢谢

**Comment by Justineo** [comment]
实际上 MDN 自己也是社区贡献的翻译，可能没有固定标准，比如[这里](https://developer.mozilla.org/zh-CN/docs/Web/Accessibility/ARIA#:~:text=%E4%B8%AD%E7%9A%84%E5%8F%AF%E8%AE%BF%E9%97%AE-,%E5%AF%BC%E8%88%AA%E5%9C%B0%E6%A0%87,-%E3%80%81JavaScript%20%E5%B0%8F%E9%83%A8%E4%BB%B6)就把“navigation landmarks”翻译成了“导航地标”。

**Comment by wxsms** [comment]
> 实际上 MDN 自己也是社区贡献的翻译，可能没有固定标准，比如[这里](https://developer.mozilla.org/zh-CN/docs/Web/Accessibility/ARIA#:~:text=%E4%B8%AD%E7%9A%84%E5%8F%AF%E8%AE%BF%E9%97%AE-,%E5%AF%BC%E8%88%AA%E5%9C%B0%E6%A0%87,-%E3%80%81JavaScript%20%E5%B0%8F%E9%83%A8%E4%BB%B6)就把“navigation landmarks”翻译成了“导航地标”。

确实。不过现在 Jinjiang 为英文版发的 PR 给 landmark 加上了 mdn 的链接，感觉可理解性好了很多。针对这个 issue 所提到的 landmark 这个仅出现在 accessibility 章节的词来说的话，感觉是否翻译区别都不大了。

**Comment by Jinjiang** [comment]
> 实际上 MDN 自己也是社区贡献的翻译，可能没有固定标准，比如[这里](https://developer.mozilla.org/zh-CN/docs/Web/Accessibility/ARIA#:~:text=%E4%B8%AD%E7%9A%84%E5%8F%AF%E8%AE%BF%E9%97%AE-,%E5%AF%BC%E8%88%AA%E5%9C%B0%E6%A0%87,-%E3%80%81JavaScript%20%E5%B0%8F%E9%83%A8%E4%BB%B6)就把“navigation landmarks”翻译成了“导航地标”。

确实，MDN 其实自身也有翻译的问题和所需的相关讨论
有争议的地方我们可以再讨论吧，总体上基于 MDN 的译法会让我们的译法讨论更轻松有效一些，另外 landmark 确实翻译成地标大家可能更疑惑，具体到这个词我个人倾向于先不翻译了，另外我发 PR 到原文加上了 landmark 的 MDN 链接，这样会更方便理解。

谢谢

**Comment by Jinjiang** [comment]
鉴于相关改动已经全部生效，这里将 issue 关闭
谢谢
