### ISSUE TITLE
导航栏在浏览器窗口宽度较小时文本折行的问题

### ISSUE THREAD

**Issue by millker** [vuejs-translations/docs-zh-cn#271]
在浏览器宽度为:770~800px之间时，导航栏会有样式问题。

**Comment by KiritaniAyaka** [comment]
768~782px

![image](https://user-images.githubusercontent.com/26200808/163668454-523d4b1b-dd5c-48d9-aacb-172509905b9b.png)

**Comment by millker** [comment]
我发现这应该是：https://github.com/vuejs/theme 的问题，我的想法是修改theme中所有的@media到800px...
或者有没有其它什么办法..
![ZW_2IJ3`55)ZRNT3$9NX$YL](https://user-images.githubusercontent.com/72451061/163676762-2051f06f-7393-485c-9f39-7c11daff29e9.png)

**Comment by KiritaniAyaka** [comment]
768px 这些断点好像是从 Bootstrap 那时候留下来的规范，改这个感觉不太好。

在开发者工具里试了下，在 `.vt-flyout-button-text` 和 `.VPNavBarMenuLink` 中添加 `white-space: nowrap` 可以解决。

但是不知道能不能针对中文文档独立修改这个样式，还是说必须要改 VitePress 主题那边的代码。

![image](https://user-images.githubusercontent.com/26200808/163678730-40b5e2ec-70dc-4fe6-9062-d3c981a69009.png)
![image](https://user-images.githubusercontent.com/26200808/163678753-a2c190d2-a600-4ee2-8d2b-53c277ad0826.png)
![image](https://user-images.githubusercontent.com/26200808/163678811-bc0c0e44-3061-4b23-ac61-f7d8386eeb0c.png)

**Comment by millker** [comment]
你说的很对，我照着你的思路，在.vitepress/theme/styles/ 下新建了nav.css文件，在这里给VPNavBarMenue添加样式后，然后在index.css中引入，很好的解决了这个问题。

**Comment by KimYangOfCat** [comment]
个人认为这个问题既然是由 vitepress 默认主题引起的，可以先尝试在上游主题仓库中去提交 PR 修复它，如果上游拒绝合并，再考虑在本仓库单独处理。

**Comment by millker** [comment]
> 个人认为这个问题既然是由 vitepress 默认主题引起的，是不是可以先尝试在[上游主题仓库](https://github.com/vuejs/theme)中去提交 PR 修复它？ 如果上游拒绝合并，再考虑在本仓库单独处理。

好的。

**Comment by Jinjiang** [comment]
认同，建议在 vitepress 先讨论，然后我们这边保持更新即可

**Comment by Jinjiang** [comment]
同步一下，我发现这个问题 `@vue/theme` 已经修复了，估计下次再发新版本的时候我们这边更新版本后就可以了
https://github.com/vuejs/theme/pull/59
