### ISSUE TITLE
Wiki 协作指南中链接过时

### ISSUE THREAD

**Issue by KiritaniAyaka** [vuejs-translations/docs-zh-cn#274]
[Wiki 协作指南 3.1](https://github.com/vuejs-translations/docs-zh-cn/wiki/%E5%8D%8F%E4%BD%9C%E6%8C%87%E5%8D%97#31-%E7%BF%BB%E8%AF%91%E5%92%8C%E6%A0%A1%E5%AF%B9) 中 `这个 GitHub Project 页面` 指向的仍是已经被 close 的 Guide 翻译进度 Project Board。

其实可以修改为 [Project 面板链接](https://github.com/vuejs-translations/docs-zh-cn/projects) 避免后续频繁修改，反正默认不展示已经 close 的 Project ，即使以后同时有多个翻译项目进行也可以同时展示。

**Comment by Jinjiang** [comment]
已更新。谢谢
