### ISSUE TITLE
关于定冠词翻译统一问题

### ISSUE THREAD

**Issue by KiritaniAyaka** [vuejs-translations/docs-zh-cn#286]
英语中 `a` `an` `the` 等定冠词是很常见的，但咱目前发现在现有文档中关于定冠词的翻译并不统一。

个人认为**多数情况下**定冠词可直接省略，少数情况可翻译为 `a` / `an` -> `一个` 、`the` -> `这个`。如果全部显式翻译，由于定冠词本身无实义，会导致句子冗长且阅读难度提高。

咱在校对 [`options-lifecycle.md`](https://github.com/vuejs-translations/docs-zh-cn/blob/main/src/api/options-lifecycle.md) 时发现原翻译大量显式地翻译了定冠词，在尊重原翻译、不作大幅修改的前提下，没有删除这些定冠词。

但在后续校对 [`composition-api-lifecycle.md`](https://github.com/vuejs-translations/docs-zh-cn/blob/main/src/api/composition-api-lifecycle.md) 时，却又在与 [`options-lifecycle.md`](https://github.com/vuejs-translations/docs-zh-cn/blob/main/src/api/options-lifecycle.md) 内容相同的地方发现了不翻译（直接省略）定冠词的做法。

目前是否有必要统一定冠词译法？如果有，应当采用哪种译法？

**Comment by Justineo** [comment]
我觉得在不影响原文意思的情况下，可以尽量使用符合中文习惯的译法，全部显式翻译出来应该是没有必要的。

**Comment by KiritaniAyaka** [comment]
> 我觉得在不影响原文意思的情况下，可以尽量使用符合中文习惯的译法，全部显式翻译出来应该是没有必要的。

赞同，翻译首要的就是要准确传达原文意思。

咱个人对于定冠词翻译一些情况的建议：

1. `the` + 名词 如果在上下文中特指某一个事物，翻译成 `这个`。
2. `a` / `an` + 名词 如果不是泛指（如特指或强调个数），可以翻译成 `一个`。
3. 其他情况尽可能地减少显式翻译的定冠词个数。

如果没问题的话咱自己会按照这个建议走，也希望可以给其他翻译者们作为参考。大家也可以提出更好或者更详细的建议。

**Comment by Jinjiang** [comment]
我也觉得没有必要统一，翻译本身就不是逐字逐句直译，句子本身通顺无歧义足矣。谢谢
