### ISSUE TITLE
项目起步

### ISSUE THREAD

**Issue by ShenQingchuan** [vuejs-translations/docs-zh-cn#3]
由于英文文档处于非常快的迭代周期（几乎平均每天更新）之中，因此为保证一些基本的同步：

- 我 @ShenQingchuan 可能于最近一段时间在此仓库自发主持同步英文代码的相关工作（一般是一些样式更改、Vitepress 的依赖升级、配置文件的修改以及内嵌组件的代码更新，对中文文档所呈现的内容影响没有或很小），这会是一些直接在 main 分支上的推送。

- 在此期间，我不会直接推送任何新的整篇文档翻译到本仓库。（但可能有一些必要的增补翻译会直接修改+推送）任何新的主要中文内容都会走工作组的 CR 流程。

同步的过程中我将会在这个 issue 中追帖、记录同步的相关过程，并注明必要的、需要知会和说明的细节。

**Comment by Jinjiang** [comment]
我抽空简单整理了一下截至目前中英文仓库的比对结果，并可以长期保持它的更新，希望可以方便大家进一步追踪和审阅

该统计基于截止到目前的最新提交
- en https://github.com/vuejs/docs/commit/f5a38e3a4288e825d7bde6b7f5e4eea3729831e4
- zh-cn https://github.com/vuejs-translations/docs-zh-cn/commit/c84ad4c800ad8a67a7dcb0e20313964da20d3cd5

除了 `src/**/*.md` 的不同 (包括 `src/.vitepress` 算是个灰度区域)，我建议核实一下改动或不同的原因，包括只有 zh-cn 或 en 有的 md 文件，这样大家在理解这些改动的基础上可以专注在内容翻译和校对上：）

这部分可能得有劳 @ShenQingchuan 稍微核实补充一下

谢谢

----

### Site/repo Config

#### `<root>`

- Files are different:
  - `package.json` 主要是为了修改 build 脚本，另外加入了 clean 脚步，同时增加相关三方依赖
  - `pnpm-lock.yaml` 基于 `package.json` 更新 lock file
  - `README.md` 中文版 README 重写

#### `.github`

- File `scripts/tag-alert-blocks.js` is different
- File `workflows/deploy.yml` is only in **zh-cn** repo

#### `scripts`

- File `scripts/build.js` is only in **zh-cn** repo 主要是在原有的 build 脚本基础上增加了 `src/.vitepress/rewrite-title.js` 的执行逻辑

#### `src/.vitepress`

- File `config.ts` is different 中文翻译 + 增加“语言”子菜单 + algolia 中文版参数 + 注释掉了 `vue.compilerOptions.directiveTransforms` (why?)
- File `headerMdPlugin.ts` is different 
- File `render-perma-link/index.js` is only in **zh-cn** repo
- File `rewrite-title/index.js` is only in **zh-cn** repo
- File `theme/components/Banner.vue` is different 仅中文翻译
- File `theme/components/NewsLetter.vue` is different 仅中文翻译
- File `theme/components/PreferenceSwitch.vue` is different 仅中文翻译
- File `theme/index.ts` is different
- File `theme/styles/scrollbar.css` is only in **zh-cn** repo
- File `utils/frontmatter-service.js` is only in **zh-cn** repo

### Content

- File `src/about/translation.md` is only in **zh-cn** repo 翻译说明
- File `src/api/index.json` is only in **en** repo
- Files are different:
  - `src/api/api.data.ts`
  - `src/api/ApiIndex.vue`
- File `src/examples/data.json` is only in **en** repo
- File `src/public/images/italic-demo.png` is only in **zh-cn** repo
- File `src/publicimages/link-with-around-spaces.png` is only in **zh-cn** repo
- File `src/publicimages/link-without-around-spaces.png` is only in **zh-cn** repo

### MD files are different:

- `src/guide/**/*.md` 英文版文档已经稳定，可以着手翻译和校对
- `src/index.md`
- `src/about/coc.md`
- `src/about/team.md`
- `src/api/application.md`
- `src/api/built-in-components.md`
- `src/api/built-in-directives.md`
- `src/api/built-in-special-attributes.md`
- `src/api/built-in-special-elements.md`
- `src/api/component-instance.md`
- `src/api/general.md`
- `src/api/options-composition.md`
- `src/api/options-lifecycle.md`
- `src/api/options-misc.md`
- `src/api/options-rendering.md`
- `src/api/options-state.md`
- `src/api/reactivity-advanced.md`
- `src/api/reactivity-core.md`

**Comment by veaba** [comment]
进度：
- [x] 从 docs-next-zh-cn 迁移 label  
- [x] 从 docs-next-zh-cn 迁移 wiki （翻译须知部分）
- [x]  从 docs-next-zh-cn 迁移 projects card（等楼上部分确认）

**Comment by wxsms** [comment]
- [x] sync script

**Comment by veaba** [comment]
- [x] 迁移 sr/guide/**.md 文件的 追踪至 [projects/未认领校对](https://github.com/vuejs-translations/docs-zh-cn/projects/1#column-17440749)

**Comment by Jinjiang** [comment]
更新：我留意到现在社区已经有人开始参与校对翻译了，经过跟大家小范围线下讨论，创建了一个和翻译之前版本文档的时候相同的“集中翻译和校对工作汇总”issue #8 并置顶，同时将这里的标题改为“项目起步”。谢谢

**Comment by Jinjiang** [comment]
鉴于项目起步的工作基本都已经完成，site config / project config 也刚刚通过 @yyx990803 同步到最新，我觉得这里的讨论可以收敛了。不介意的话我直接关掉了。

谢谢
