### ISSUE TITLE
[认领][已翻译未校对]: src/guide/components/props.md

### ISSUE THREAD

**Issue by Husky-Yellow** [vuejs-translations/docs-zh-cn#32]
认领 [card-75930834](https://github.com/vuejs-translations/docs-zh-cn/projects/1#card-75930834)

**Comment by Jinjiang** [comment]
@Husky-Yellow 你认领的这篇已经翻译过了 https://staging-cn.vuejs.org/guide/components/props.html 你可以选择校对该文档或翻译其它未翻译的文档。谢谢
