### ISSUE TITLE
文字错误

### ISSUE THREAD

**Issue by threeStepWalk** [vuejs-translations/docs-zh-cn#340]
位置： /api/options-misc.html#name

原文：另一种场景是裆一个组件通过 [app.component](https://staging-cn.vuejs.org/api/application.html#app-component) 被全局注册时，这个全局 ID 就自动被设为了其名称。

错误：“裆”

**Comment by wxsms** [comment]
欢迎使用页面上的“在 GitHub 上编辑此页”功能直接提交PR！

**Comment by threeStepWalk** [comment]
已提
