### ISSUE TITLE
官网的 Codesandbox 打不开

### ISSUE THREAD

**Issue by makesense2022** [vuejs-translations/docs-zh-cn#343]
<img width="539" alt="image" src="https://user-images.githubusercontent.com/105351062/168270578-a4965e67-fa66-4d1c-b6d6-b7d8d52ccc2e.png">
<img width="660" alt="image" src="https://user-images.githubusercontent.com/105351062/168270594-8da987e7-c4d2-4635-9429-d203b8e80f2b.png">

**Comment by Jinjiang** [comment]
@makesense2022 你在哪里看到这些内容的？可以贴一下链接吗？谢谢

**Comment by makesense2022** [comment]
> @makesense2022 你在哪里看到这些内容的？可以贴一下链接吗？谢谢

https://v3.cn.vuejs.org/guide/migration/introduction.html#%E6%A6%82%E8%A7%88

**Comment by Jinjiang** [comment]
了解了

事实上新版文档里已经没有这个链接了。你看到的版本对应的旧版仓库在这里
https://github.com/vuejs/docs-next-zh-cn/
