### ISSUE TITLE
页面刷新时，网页标题会先显示”404 | Vue.js“，再显示正常标题

### ISSUE THREAD

**Issue by GanZhiXiong** [vuejs-translations/docs-zh-cn#349]
<img width="365" alt="image" src="https://user-images.githubusercontent.com/27394631/169096293-00d65db6-1761-454c-950a-4faa83c225bd.png">

**Comment by Jinjiang** [comment]
这个问题现在还有吗？我这边重现不了

**Comment by GanZhiXiong** [comment]
我刚试了下，没有了，这个问题是怎么修复的呢？

**Comment by Jinjiang** [comment]
我其实什么也没做，也没有重现过这个问题……

**Comment by GanZhiXiong** [comment]
官网 https://staging-cn.vuejs.org/ 现在确实没有这个问题了，但是 2 天前这个还是存在的，之前的代码部署在这里了 https://docs-zh-ggwroyafb-go-studio.vercel.app/，你可以打开该链接，刷新页面就可以复现该问题。

**Comment by Jinjiang** [comment]
这有点难解释……也许只是一个底层的依赖更新导致的
不介意的话我们先把这个 issue 关掉好了，毕竟现在最新的部署没有这个问题，等官网再复现这个问题的时候我们可以再 reopen 继续排查

**Comment by GanZhiXiong** [comment]
ok，木问题

**Comment by GanZhiXiong** [comment]
@Jinjiang 

将 vitepress 从 v0.22.3 更新到 v0.22.4后，就没有这个问题了。
看来是 vitepress v0.22.3 的问题。
