### ISSUE TITLE
关于代码文本翻译问题的讨论

### ISSUE THREAD

**Issue by KimYangOfCat** [vuejs-translations/docs-zh-cn#35]
@Jinjiang 提议 [代码文本不翻译，只翻译注释](https://github.com/vuejs-translations/docs-zh-cn/pull/6#issuecomment-1013804702)
@wxsms 指出 [此处](https://github.com/vuejs-translations/docs-zh-cn/pull/7#discussion_r788747750) 也可不翻译文本

但此处代码有一点儿特殊的是它带有结果展示，我不知道如果是纯示例代码，我认为不翻译代码文本也可，但若是有结果展示，这些代码文本最终也会变为文档页面的文本，此时不翻译，我感觉就有些不和谐了，效果如下：
![image](https://user-images.githubusercontent.com/32960305/150595387-879fd0e4-f80a-4361-9f15-8290bea1c529.png)

不知道大家如何看待这个问题呢？是否需要统一代码文本和注释都翻译？还是代码文本不翻译，只翻译注释？再或者带了展示结果的代码文本和注释才翻译？

**Comment by wxsms** [comment]
我赞同 Jinjiang 的建议。文档的目标人群应该是要有一定的英语基础的，这类代码块带有少量的、通常来说是常见词汇的英文，我觉得影响不大。

**Comment by Justineo** [comment]
建议不要翻译了，比较容易统一标准，而且代码内容里的英文描述一般不太可能引起理解上的困难。

**Comment by KimYangOfCat** [comment]
好叭，既然大家认为不翻译也没关系，那就不翻译吧，相关pr，我会一一修改

**Comment by KimYangOfCat** [comment]
前面提到的相关处代码均已修改，此 issue 可关闭了
