### ISSUE TITLE
quick-start未翻译部分

### ISSUE THREAD

**Issue by ch1lam** [vuejs-translations/docs-zh-cn#364]
markdown文件中未见标记
请问这部分是不作翻译吗？

![1](https://user-images.githubusercontent.com/39334548/169687875-52eff723-72ae-43ef-9d68-066005fbc385.jpeg)
![2](https://user-images.githubusercontent.com/39334548/169687876-c4deb5d5-a3f4-4e00-bb57-11e36a12ebdd.jpeg)

**Comment by Jinjiang** [comment]
理论上应该是翻译完以后，英文版又更新了的新内容是应该翻译的，欢迎贡献。
