### ISSUE TITLE
关于 computed ref 的翻译

### ISSUE THREAD

**Issue by KimYangOfCat** [vuejs-translations/docs-zh-cn#40]
请参考[此处](https://github.com/vuejs-translations/docs-zh-cn/pull/22/files/13c02b2bab47319a979054fe3703a27a0db8b059#r790219247)

目前翻译为：计算 ref

大家还有其他想法吗？提议吗？

这也算是Vue中的一个术语，希望得到讨论然后整合进术语约定。

**Comment by wxsms** [comment]
按照目前的术语翻译约定，computed 应该翻译为“计算属性”，因此 computed ref 应该翻译为“计算属性 ref”或“计算属性引用”。

不知道大家有没有更好的建议？

**Comment by Cheng-DX** [comment]
个人观点，因为vue中计算属性一直以来都是响应式的，所以之前说的Computed和现在的Computed ref含义几乎相同，是否可以直接译为计算属性并在合适的地方标注

**Comment by wxsms** [comment]
> 个人观点，因为vue中计算属性一直以来都是响应式的，所以之前说的Computed和现在的Computed ref含义几乎相同，是否可以直接译为计算属性并在合适的地方标注

据我观察，这里加 ref 应该是为了突出它在访问时需要使用 `xxx.value` 的形式，与 `ref` api 创建的变量相同，而非响应式。

**Comment by Cheng-DX** [comment]
> > 个人观点，因为vue中计算属性一直以来都是响应式的，所以之前说的Computed和现在的Computed ref含义几乎相同，是否可以直接译为计算属性并在合适的地方标注
> 
> 据我观察，这里加 ref 应该是为了突出它在访问时需要使用 `xxx.value` 的形式，与 `ref` api 创建的变量相同，而非响应式。

Got. 这样看来为了保障计算属性这个翻译不变，或许**计算属性ref**这个翻译更好

**Comment by Jinjiang** [comment]
我印象中之前一版的文档翻译过程中也讨论过，抱歉一下找不着了，结论和大家这里的一致，也就是“计算属性 ref”。
看起来我们可以达成共识了，wiki 我个人觉得也不需要特别更新，这个 issue 我直接关闭了。

谢谢大家

**Comment by KimYangOfCat** [comment]
那我去把相关翻译修改一下
