### ISSUE TITLE
Cannot set properties of undefined (setting 'name')

### ISSUE THREAD

**Issue by safeblood** [vuejs-translations/docs-zh-cn#448]
![image](https://user-images.githubusercontent.com/10238800/173285904-704a2217-ba08-4de1-89e1-5af7e989f709.png)

**Comment by Jinjiang** [comment]
该错误取决于你实际练习的时候撰写的代码，这里只讨论文档翻译，并不用于解答实际练习中遇到的问题，谢谢

**Comment by safeblood** [comment]
> 该错误取决于你实际练习的时候撰写的代码，这里只讨论文档翻译，并不用于解答实际练习中遇到的问题，谢谢

我直接npm run serve之后就是这个样子啊，输入框里面的代码我没改过啊
