### ISSUE TITLE
api index page render error

### ISSUE THREAD

**Issue by fansheng0594** [vuejs-translations/docs-zh-cn#452]
https://staging-cn.vuejs.org/api/
<img width="400" alt="image" src="https://user-images.githubusercontent.com/32379148/175803259-c64f7cfe-06d5-4163-a172-334c56870667.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/32379148/175803282-f5745451-232a-4e1b-98e1-95b6f22e16c8.png">

https://github.com/vuejs-translations/docs-zh-cn/blob/main/src/api/ApiIndex.vue#L98

**Comment by KimYangOfCat** [comment]
我在本地拉取了 main 分支，本地开启 dev，以及 build 后的文件都是正常的，没有出现这个问题，暂时没有定位出来这个问题的原因，进一步定位的话，可以是看看是否是 Actions 编译的问题

系统：macOS 12.1
Node：v16.14.2
