### ISSUE TITLE
中文文档打不开了？

### ISSUE THREAD

**Issue by gastrodia** [vuejs-translations/docs-zh-cn#463]
[https://staging-cn.vuejs.org/](https://staging-cn.vuejs.org/) 打不开

**Comment by itchaox** [comment]
我也遇到这个问题了

itchao
2022年7月9日23:49:24

**Comment by veaba** [comment]
https://staging-cn.vuejs.org/ 已恢复。

**Comment by itchaox** [comment]
> https://staging-cn.vuejs.org/ 已恢复。

好的，谢谢
