### ISSUE TITLE
请问下 Vue3 官方打包构建工具是 Webpack 还是 Vite？ 谢谢！

### ISSUE THREAD

**Issue by itchaox** [vuejs-translations/docs-zh-cn#464]
问题：
我在 Vue3 旧官网看到打包工具是 Webpack，在 Vue3 新官网看到打包构建工具是 Vite 所以比较迷惑，如果在公司开发 Vue3  + ts 项目的话，是使用 Webpack 好，还是直接使用 Vite 比较好（比较急，如果能回答一下，万分感谢！！！）

谢谢！！！

itchao
2022年7月10日00:16:57

**Comment by gastrodia** [comment]
新官网是用的[vitepress](https://github.com/vuejs/vitepress)

**Comment by itchaox** [comment]
> 新官网是用的[vitepress](https://github.com/vuejs/vitepress)

那我在公司新项目是直接用 Vite 就行吗？
谢谢

itchao

2022年7月10日10:03:53

**Comment by gastrodia** [comment]
> > 新官网是用的[vitepress](https://github.com/vuejs/vitepress)
> 
> 那我在公司新项目是直接用 Vite 就行吗？ 谢谢
> 
> itchao
> 
> 2022年7月10日10:03:53

是的，可以的，我已经用了一年多了。

**Comment by itchaox** [comment]
> > > 新官网是用的[vitepress](https://github.com/vuejs/vitepress)
> > 
> > 
> > 那我在公司新项目是直接用 Vite 就行吗？ 谢谢
> > itchao
> > 2022年7月10日10:03:53
> 
> 是的，可以的，我已经用了一年多了。

你也是在公司做项目用的吗？好的谢谢

**Comment by gastrodia** [comment]
> > > > 新官网是用的[vitepress](https://github.com/vuejs/vitepress)
> > > 
> > > 
> > > 那我在公司新项目是直接用 Vite 就行吗？ 谢谢
> > > itchao
> > > 2022年7月10日10:03:53
> > 
> > 
> > 是的，可以的，我已经用了一年多了。
> 
> 你也是在公司做项目用的吗？好的谢谢

是的，公司项目

**Comment by itchaox** [comment]
> > > > > 新官网是用的[vitepress](https://github.com/vuejs/vitepress)
> > > > 
> > > > 
> > > > 那我在公司新项目是直接用 Vite 就行吗？ 谢谢
> > > > itchao
> > > > 2022年7月10日10:03:53
> > > 
> > > 
> > > 是的，可以的，我已经用了一年多了。
> > 
> > 
> > 你也是在公司做项目用的吗？好的谢谢
> 
> 是的，公司项目

好的，谢谢

**Comment by itchaox** [comment]
那这个问题应该在哪里反馈了？？

**Comment by MaNewB** [comment]
@itchaox 应该去英文文档哪里，这只是个翻译

**Comment by itchaox** [comment]
> 

好的，谢谢
