### ISSUE TITLE
服务器崩了？还是在维护？

### ISSUE THREAD

**Issue by lindong-h** [vuejs-translations/docs-zh-cn#465]
又到看英文文档的时候了,（官方中文文档已恢复）

**Comment by mafqla** [comment]
加一，我也打不开了。vite文档也是。

**Comment by adlkt** [comment]
mark

**Comment by veaba** [comment]
看起来是 Gitee 搞事情了。

**Comment by MagmaBlock** [comment]
好难受，只能先用英文文档了，vue、vue router 的文档都打不开了

**Comment by aliujun** [comment]
+1，好难受，什么时候才能恢复啊

**Comment by ac123cm** [comment]
可以跑本地的先用着。还不知道多久恢复好

**Comment by zhch-hong** [comment]
> +1，好难受，什么时候才能恢复啊

clong源码，跑本地可以的

**Comment by wxsms** [comment]
https://v3.cn.vuejs.org/

提供一个替代选项，目前旧版 v3 文档仍然可以访问。

**Comment by ac123cm** [comment]
> 可以跑本地的先用着。还不知道多久恢复好

已经恢复好了

**Comment by veaba** [comment]
已恢复了，大家可以访问了：https://staging-cn.vuejs.org/ 。

这个 issue 这边 close 掉。

**Comment by veaba** [comment]
你好先生/女士！     当你看到本回复，说明你的邮件我已经收到，我会尽快回复处理你的邮件，祝你愉快。      ***@***.***
