### ISSUE TITLE
关于超链接的一些问题

### ISSUE THREAD

**Issue by xi479** [vuejs-translations/docs-zh-cn#474]
可不可以规定超链接前后添加空格，我看这方面并没有达成共识，可以说有点混乱

**Comment by Justineo** [comment]
这个我们已有共识，链接和加不加空格无关，加空格只在中英文混排场景下使用。如果你发现了不一致的情况，欢迎提出 or PR。

**Comment by xi479** [comment]
某些情况下这样会很丑，例如：
在[组合式 API FAQ](https://staging-cn.vuejs.org/guide/extras/composition-api-faq.html) 章节中，你可以了解更多关于这两种 API 风格的对比以及组合式 API 所带来的潜在收益。
好像字歪了一样

**Comment by xi479** [comment]
如果在组字前面补一个空格会好很多

**Comment by Justineo** [comment]
“很丑”是主观的，在目前已经达成共识的风格上我们暂时还是先保持一致。
