### ISSUE TITLE
校对同一篇文章能够多次PR吗？

### ISSUE THREAD

**Issue by yyb1rd** [vuejs-translations/docs-zh-cn#49]
我想校对一篇文章时，迭代工作——从用词错误，然后长句拆散，之后修改一些欧化的表达，最后润色一些过渡句。

修改到后期，争议越大，个人色彩可能会更浓，修改的范围也会更多。而且似乎有规定，不接受一次性大改。所以想拆成多次PR，也便于其他人检查我的工作。

但如此一来，就需要多次PR。可我看过往的PR，没有多次PR的。这就有了疑惑：

多次PR无疑增加我和管理员的工作量，是否有更优的方式？

如果要多次PR，需要重新发布 Issues “[认领][校对]”吗？

**Comment by wxsms** [comment]
你好，请以一个 md 文件为单位发起校对即可，可以一次性提出！上次的 PR 主要是 changes 太多了（200 多个），一个 PR 以一个 md 文件的 changes 为最佳，感谢你的贡献！

**Comment by veaba** [comment]
补充楼上，不必重复重新发起 [认领/校对] 申请的 issue。
