### ISSUE TITLE
view a empty page 

### ISSUE THREAD

**Issue by w1217358955** [vuejs-translations/docs-zh-cn#498]
你打开了一个不存在的链接：/style-guide/。

**Comment by wxsms** [comment]
建议报告 issue 的时候尽可能准确地描述复现路径。比如具体到这个 issue，你是如何打开这个页面的，点了页面上哪个链接，等等。有一个复现的 gif/视频则更佳。谢谢。

**Comment by Jinjiang** [comment]
应该是新版上线过程中旧版的缓存导致的，这个链接在新版文档里是不存在的。
