### ISSUE TITLE
transition 404

### ISSUE THREAD

**Issue by 851091009** [vuejs-translations/docs-zh-cn#516]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

页面 404
![微信截图_20220823182122](https://user-images.githubusercontent.com/8460036/186134558-0af14224-da29-449e-b253-0bb94459afd2.png)

**Comment by Justineo** [comment]
https://cn.vuejs.org/guide/built-ins/transition.html

看起来这个链接是有效的，你能给一下复现路径吗？（比如点了哪个链接出现的报错）

**Comment by 851091009** [comment]
> https://cn.vuejs.org/guide/built-ins/transition.html
> 
> 看起来这个链接是有效的，你能给一下复现路径吗？（比如点了哪个链接出现的报错）
这会再看已经正常了，不知道是什么原因！！
