### ISSUE TITLE
插槽页面404

### ISSUE THREAD

**Issue by Galen-xiaogao** [vuejs-translations/docs-zh-cn#518]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

![image](https://user-images.githubusercontent.com/44578409/186304929-6f1e3364-7a2e-46b3-808e-e8bac1f15ded.png)

**Comment by itsyuxuan** [comment]
页面没有问题

<img width="1001" alt="截屏2022-08-24 上午10 54 42" src="https://user-images.githubusercontent.com/62364938/186310427-aca50ffe-0c5c-4dd5-b6f3-adba55a86116.png">

**Comment by wxsms** [comment]
建议尝试清除（浏览器、DNS）缓存并刷新。

**Comment by Jinjiang** [comment]
应该是缓存问题，刷新之后可以恢复，属于已知现象。如果问题仍无法解决，可以重开或新开 issue 讨论。谢谢
