### ISSUE TITLE
Vue2迁移到Vue3的迁移文档无法访问中文版

### ISSUE THREAD

**Issue by alinemeng** [vuejs-translations/docs-zh-cn#521]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

从Vue3官方中文文档 [https://cn.vuejs.org/guide/introduction.html](https://cn.vuejs.org/guide/introduction.html)点击**迁移指南**跳转的是英文的迁移指南，我尝试了各种切换方法无法切换成中文的。

**Comment by wxsms** [comment]
https://github.com/vuejs-translations/docs-zh-cn/issues/519#issuecomment-1225844450
