### ISSUE TITLE
文档透传 Attributes 入口进入404

### ISSUE THREAD

**Issue by leehave** [vuejs-translations/docs-zh-cn#523]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

![image](https://user-images.githubusercontent.com/16717693/187062661-2cbf2f83-3bda-4578-b72c-5c9dd94d2686.png)
https://staging-cn.vuejs.org/guide/components/attrs.html
文档[透传 Attributes](https://staging-cn.vuejs.org/guide/components/attrs.html)入口进入404

**Comment by itsyuxuan** [comment]
staging-cn.vuejs.org 的内容已经过时，请访问正式版本的官方文档 [http://cn.vuejs.org](http://link.zhihu.com/?target=http%3A//cn.vuejs.org)
