### ISSUE TITLE
网页404

### ISSUE THREAD

**Issue by guijue-code** [vuejs-translations/docs-zh-cn#527]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

<img width="905" alt="image" src="https://user-images.githubusercontent.com/66724249/187410776-15cb18b5-c88b-4bf3-adbe-0472ad7148f3.png">
关于单元测试的网页404

**Comment by Jinjiang** [comment]
已知问题，我们将汇总到这里处理并追踪，谢谢 https://github.com/vuejs/v2.cn.vuejs.org/issues/1222

**Comment by guijue-code** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vuejs-translations/docs-zh-cn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月30日(星期二) 晚上9:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vuejs-translations/docs-zh-cn] 网页404 (Issue #527)





 
已知问题，我们将汇总到这里处理并追踪，谢谢 vuejs/v2.cn.vuejs.org#1222

**Comment by guijue-code** [comment]
嗯嗯，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vuejs-translations/docs-zh-cn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月30日(星期二) 晚上8:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vuejs-translations/docs-zh-cn] 网页404 (Issue #527)





 
https://cn.vuejs.org/v2/guide/migration-vuex.html 类似。
 

 
通过搜索 mutations 得到该页面入口：
