### ISSUE TITLE
搜索渲染函数跳转页面404

### ISSUE THREAD

**Issue by lwh795** [vuejs-translations/docs-zh-cn#532]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

[
<img width="990" alt="image" src="https://user-images.githubusercontent.com/20041248/187649633-8d0878af-6337-44f3-b449-a7a89c70aadf.png">
](url)
搜索渲染函数，点击跳转渲染函数404

**Comment by Jinjiang** [comment]
你说的应该是 v2 的搜索，是另外一个仓库，目前已经有 issue 在跟进了
https://github.com/vuejs/v2.cn.vuejs.org/issues/1222

谢谢
