### ISSUE TITLE
Runtime + Compiler vs. Runtime only 链接404 了…… 

### ISSUE THREAD

**Issue by sphenginx** [vuejs-translations/docs-zh-cn#533]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

链接失效或者缺失。

### 问题描述

在阅读文档 https://cli.vuejs.org/zh/config/#runtimecompiler 时， 有个 更多细节可查阅：[Runtime + Compiler vs. Runtime only](https://cn.vuejs.org/v2/guide/installation.html#%E8%BF%90%E8%A1%8C%E6%97%B6-%E7%BC%96%E8%AF%91%E5%99%A8-vs-%E5%8F%AA%E5%8C%85%E5%90%AB%E8%BF%90%E8%A1%8C%E6%97%B6) 的说明， 点击  `Runtime + Compiler vs. Runtime only` 链接时 显示 404 页面未找到，如下图所示：

![1661999387093](https://user-images.githubusercontent.com/1829395/187819554-54bdab39-5656-47cd-af16-19fbd658196b.png)

**Comment by Gavrain** [comment]
这是由于这个链接指向了vue2的一个页面，而vue2的doc已经迁移到 v2.cn.vuejs.org 上，你可以通过手动替换域名来访问这个页面，如：https://v2.cn.vuejs.org/v2/guide/installation.html#运行时-编译器-vs-只包含运行时。

同样的，由于中文版的域名没有替换，vue2的文档搜索功能也被破坏。

**Comment by wxsms** [comment]
已发起 PR 修复该问题，同时因为该问题并非属于本仓库，因此先关闭了。
