### ISSUE TITLE
配置文档链接点击跳转错误

### ISSUE THREAD

**Issue by baozhi000** [vuejs-translations/docs-zh-cn#546]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

![image](https://user-images.githubusercontent.com/41611460/190948067-5ed3a6fa-c609-4b83-bc8d-9cf349ed038b.png)
提示信息：
![image](https://user-images.githubusercontent.com/41611460/190948097-cff9bf8f-ae6f-437a-9403-81c6ec28d1ce.png)

**Comment by Jinjiang** [comment]
这个应该是 CLI 文档的问题，可以来这里直接发 PR 进行修改
https://github.com/vuejs/vue-cli/blob/dev/docs/zh/config/index.md

**Comment by wxsms** [comment]
> 这个应该是 CLI 文档的问题，可以来这里直接发 PR 进行修改 https://github.com/vuejs/vue-cli/blob/dev/docs/zh/config/index.md

我已经发了 PR：https://github.com/vuejs/vue-cli/pull/7287
