### ISSUE TITLE
《Vue 文档编写指南》docs-zh-cn/.github/contributing/writing-guide.md 文件需要恢复

### ISSUE THREAD

**Issue by xianghongai** [vuejs-translations/docs-zh-cn#551]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

《Vue 文档编写指南》docs-zh-cn/.github/contributing/writing-guide.md 文件需要恢复。
它有重要意义。

**Comment by Jinjiang** [comment]
需要恢复是什么意思？现在这个文件是存在的
https://github.com/vuejs-translations/docs-zh-cn/blob/main/.github/contributing/writing-guide.md

**Comment by xianghongai** [comment]
翻译版，以前加书签过，有对应的翻译版。
