### ISSUE TITLE
可以添加下载为pdf的功能吗

### ISSUE THREAD

**Issue by jexjws** [vuejs-translations/docs-zh-cn#564]
我是一位普通的vue学习者，我希望给网站添加一个“将所有 深度教程/api 用例以pdf 格式下载”的功能，以方便打印店打印（在设备受限的环境下阅读资料）

**Comment by Justineo** [comment]
谢谢，我们不推荐通过这种离线方式访问文档，因为它无法即时获取内容更新。真的要本地访问你可以 clone 此项目然后用开发模式启动。
