### ISSUE TITLE
内置组件 transition 和 transition-group 页面 404

### ISSUE THREAD

**Issue by morelearn1990** [vuejs-translations/docs-zh-cn#569]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [ ] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

https://cn.vuejs.org/guide/built-ins/transition-group.html
https://cn.vuejs.org/guide/built-ins/transition.html

两个页面 404

**Comment by wxsms** [comment]
see #518
