### ISSUE TITLE
vue3文档路由篇章错别字 

### ISSUE THREAD

**Issue by wudafei01** [vuejs-translations/docs-zh-cn#579]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

![image](https://user-images.githubusercontent.com/70732213/195978174-2dd117b5-e813-4cff-bc7f-852d57681f9d.png)
https://cn.vuejs.org/guide/scaling-up/routing.html#client-side-vs-server-side-routing

**Comment by wxsms** [comment]
thanks
