### ISSUE TITLE
i18n texts: wrong i18n config object

### ISSUE THREAD

**Issue by edimitchel** [vuejs-translations/docs-zh-cn#582]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

On https://github.com/vuejs-translations/docs-zh-cn/blob/main/.vitepress/config.ts#L583, it isn't assigning the Vue theme i18n config type (`ariaSkip` is `ariaSkipToContent`).

Actually there is an issue on ariaAnnouncer which is today typed to ariaAnnouner (was fixed yesterday).
I put the [same issue on docs-ja](https://github.com/vuejs-translations/docs-ja/issues/919).

Also, I encourage you to use the `ThemeConfig['i18n']` type to avoid any surprises in the future.

**Comment by Jinjiang** [comment]
Thanks for the catches. I already created 2 PRs for both this repo and the original English docs.
