### ISSUE TITLE
手册里 transition 页面未找到

### ISSUE THREAD

**Issue by yxq477** [vuejs-translations/docs-zh-cn#584]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

网络环境和本地化

### 问题描述

点击手册里的 transition 跳转 https://cn.vuejs.org/guide/built-ins/transition.html 地址 404 
/guide/built-ins/transition-group.html 也是一样的
![image](https://user-images.githubusercontent.com/13351398/196366961-9cd1a635-8829-431a-b99c-1275d7357508.png)

**Comment by Jinjiang** [comment]
同 #518 可能是 v2 切 v3 过程中导致的，通常多刷新一下就可以了。如果还有问题可以留言或重开 issue。谢谢
