### ISSUE TITLE
v3-migration docs-zh-cn

### ISSUE THREAD

**Issue by zhousg** [vuejs-translations/docs-zh-cn#586]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

https://github.com/vuejs/v3-migration-guide/issues/18

**Comment by wxsms** [comment]
迁移指南计划待 vitepress 支持多语言后接入中文翻译。

目前可参考：https://github.com/vuejs/docs-next-zh-cn/blob/master/src/guide/migration/introduction.md

**Comment by Megasu** [comment]
👀关注该问题，请问 vitepress 什么时候支持多语言，请问日程大致是什么时候？

**Comment by Jinjiang** [comment]
建议直接在原仓库 PR 一个 zh 目录来维护，参考 Pinia：
https://github.com/vuejs/pinia/tree/v2/packages/docs

**Comment by Jinjiang** [comment]
我已经把初始化的工作做好了，欢迎大家的踊跃参与
https://github.com/vuejs/v3-migration-guide/pull/19
🙏

**Comment by zhousg** [comment]
> 我已经把初始化的工作做好了，欢迎大家的踊跃参与 [vuejs/v3-migration-guide#19](https://github.com/vuejs/v3-migration-guide/pull/19) 🙏

https://github.com/vuejs/v3-migration-guide/pull/20   已经准备好了中英配置文件，后续会持续更新
