### ISSUE TITLE
链接失效问题

### ISSUE THREAD

**Issue by XieTian000916** [vuejs-translations/docs-zh-cn#589]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [ ] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

![image](https://user-images.githubusercontent.com/114542559/197984246-0134a51a-1342-4818-8762-305771a37a44.png)
![image](https://user-images.githubusercontent.com/114542559/197984522-a4eca211-d121-49d5-a324-459369c69b95.png)
此处链接失效

**Comment by Justineo** [comment]
> 此处链接失效

方便给个链接吗？

**Comment by SkyeYoung** [comment]
![image](https://user-images.githubusercontent.com/48400568/198037637-e7f6e26f-2a8e-4f85-b448-9d59e1635962.png)

是这个页面吗？https://cn.vuejs.org/guide/components/props.html#props-declaration

![image](https://user-images.githubusercontent.com/48400568/198037930-a1e55feb-e7dd-4f79-825b-111005c21076.png)

看起来这个链接并没有问题？https://cn.vuejs.org/guide/typescript/composition-api.html#typing-component-props

**Comment by veaba** [comment]
尝试禁用下缓存，重新刷新页面。

链接是正常。

**Comment by XieTian000916** [comment]
再次试了下，是正常的了
