### ISSUE TITLE
Type 作为动词的时候的译法

### ISSUE THREAD

**Issue by Jinjiang** [vuejs-translations/docs-zh-cn#59]
目前我看到的有两种译法，个人觉得都可以 (可能还有其它译法)

- 类型化
    - the `emit` function can also be **typed** using either runtime declaration OR type declaration
    - 可以通过基于类型的声明或运行时声明让 `emit` 函数**类型化**
- 标注类型
    -  **Typing** `ref()`
    - 为 `ref()` **标注类型**

大家觉得哪个更合适，觉得是否有必要统一一下译法，或是否还有别的建议？

谢谢

**Comment by Jinjiang** [comment]
“xx化”的译法是我第一次遇到，个人觉得这样的词通常对应英文的“xxxlize”，但这里直观感觉是不错的翻译。

**Comment by Justineo** [comment]
我选“为……标注类型”。

**Comment by sudongyuer** [comment]
标注类型 我认为更佳

**Comment by ShenQingchuan** [comment]
我赞同 E0 老师的看法，

- 主动语态的形式：“为 ... 标注类型”
- 以被动语态的形式时：“被标注类型”

**Comment by Jinjiang** [comment]
那我们统一到“标注类型”吧。
稍后我来更新 wiki 并批量替换。

谢谢
