### ISSUE TITLE
官方文档 transition / transition-group 两个页面 404

### ISSUE THREAD

**Issue by Feyl** [vuejs-translations/docs-zh-cn#615]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [ ] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [ ] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

页面未找到
你打开了一个不存在的链接：/guide/built-ins/transition.html。
不介意的话请提交到[这里](https://github.com/vuejs-translations/docs-zh-cn)，我们会跟进修复。

![image](https://user-images.githubusercontent.com/68909090/205489115-5d55fc91-1e37-4ee4-a8d2-6e3b0de527f7.png)

**Comment by Feyl** [comment]
官方文档 transition / transition-group 两个页面 404

**Comment by Justineo** [comment]
方便的话请提供一下，你是点击了什么地方跳转到此 URL 的，以确保是官方文档上出现了错误的链接。

**Comment by Jinjiang** [comment]
https://cn.vuejs.org/guide/built-ins/transition.html
这个页面我这里是可以打开的，有可能是之前老版本 (v2) 缓存的问题，可以刷新一下试试，之前有过类似的 issue
参考 #518 #584
