### ISSUE TITLE
defineAsyncComponent案例存在问题

### ISSUE THREAD

**Issue by zhaozhenghao** [vuejs-translations/docs-zh-cn#619]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

![image](https://user-images.githubusercontent.com/32922591/206405301-8d7d5255-9d31-45ef-b68d-a8a33cf28eb0.png)
按照官方案例输出结构报错
![image](https://user-images.githubusercontent.com/32922591/206405552-f113afdb-2596-4d91-bba4-7dfc7edf1dee.png)
需要导出 引用的组件才行
在import 前加上return
![image](https://user-images.githubusercontent.com/32922591/206405889-c74ebd36-5b5a-4134-aac0-73fe1d1b93d8.png)

可以查看：https://juejin.cn/post/7174701271771938875

**Comment by wxsms** [comment]
我尝试了文档上的代码与你提供的代码。文档上的代码能够正常运行，你提供的、添加了 return 的代码会报语法错误（显而易见的，因为不带花括号的 arrow function 不需要也不能够加 return，这是 ES6 的基本常识之一）。

我无法评价为什么你会遇到以上问题，但建议通过 [create-vue](https://github.com/vuejs/create-vue) 创建新项目尝试以上案例。谢谢。

**Comment by wxsms** [comment]
如有疑问，可访问 [playground](https://sfc.vuejs.org/#eNp9UcFqwzAM/RXNl6TQxOxa0kLZZX+wiy9dorQpsWxkp2OE/PvkdC2jKwEfrPf0nuWnUe29Ly8Dqo2qQs2djxAwDn5nqLPecYQRGmw7wn34pvrNCUhIESZo2VnIRJsZAkO1oxDh3gXbp7o8X8FWzAGu9nlW6kSmGbKVITmVvg4iXVJEtL4/RJw11d1MS13pO6nW6upX2IMvz8GRfGhMEvNLBKM2MCMJk9dSbdQpRh82Woe2TiOcQ+n4qOVW8kCxs1hisMUnu6+ALMZGrf94aAEvyAUjNcjIS54Prf98k+1kaJKv3AJZWgpj+7CD2wpsOEr4wufZO/a9gw/HffOS0l2K9vS6G8dZPE2VlmpGO/JDhEthXYP91ijhjXrIfvoB8/HKnw==)，点击右上角 download 按钮下载到本地运行查看。
