### ISSUE TITLE
vuex v3官方文档Vue#data跳转404

### ISSUE THREAD

**Issue by achangchangchang** [vuejs-translations/docs-zh-cn#623]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

https://v3.vuex.vuejs.org/zh/guide/state.html#%E5%8D%95%E4%B8%80%E7%8A%B6%E6%80%81%E6%A0%91
该链接下的Vue#data(https://cn.vuejs.org/v2/api/#data )跳转404
![image](https://user-images.githubusercontent.com/33746006/210050237-57615276-4b52-4c41-bec5-8cfad261caf6.png)
![image](https://user-images.githubusercontent.com/33746006/210050276-4126e3c4-4e75-40dd-a233-a2efacf4423d.png)

**Comment by SkyeYoung** [comment]
It should be https://v2.cn.vuejs.org/v2/api#data 🤔
