### ISSUE TITLE
文档中的(ts)类型错误, # ref 在响应式对象中的解包

### ISSUE THREAD

**Issue by foxsir** [vuejs-translations/docs-zh-cn#634]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] #636
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

> 这个错误不是文档或者翻译的问题, 应该是vue对ts支持的问题, 这段代码在js中是没问题的, 但是ts文件就会提示错误

# 文档中示例代码(typescript)类型错误

文档链接 https://cn.vuejs.org/guide/essentials/reactivity-fundamentals.html#ref-unwrapping-in-reactive-objects

![image](https://user-images.githubusercontent.com/9588134/214765923-3cc16a66-e897-45fd-9f44-7717128fce07.png)

<img width="557" alt="image" src="https://user-images.githubusercontent.com/9588134/214765989-a3760722-06ab-48ec-b19f-fdd8f12591e8.png">

**Comment by wxsms** [comment]
1. 示例代码基于 js 编写，网站上的 playground 也是基于 js 进行的。没有保证 ts 下的兼容性我不认为这是一个“问题”。
2. 如“提问须知”所述，如果你认为这是一个问题，也应该向英文版提出 issue。

谢谢。

**Comment by foxsir** [comment]
谢谢
