### ISSUE TITLE
是否考虑对图片进行翻译？

### ISSUE THREAD

**Issue by YFengFly** [vuejs-translations/docs-zh-cn#643]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

目前图片中的英文仍未有翻译，不知道后续对此是否考虑？
以 模板语法 的 [修饰符](https://cn.vuejs.org/guide/essentials/template-syntax.html#modifiers) 为例，我用 GIMP 做了一个 Demo（使用了思源黑体）：
![directive](https://user-images.githubusercontent.com/11311708/215715937-76ef512e-a0dc-4f1d-b1c2-7cd7c16cc478.png)
但是原图是在 figma 生成并在文档中留有地址的，我这样制作位图的方式并不符合原有要求。如果不采用原先的方式，那么可能需要同时上传图片的工程文件，以便后续修改。
如果能够以原有的 figma 方式继续出翻译图，则再好不过了。

**Comment by Jinjiang** [comment]
确实我也觉得通过 figma 是比较理想的选择

**Comment by Justineo** [comment]
原文是附带了 [Figma 链接](https://github.com/vuejs/docs/blob/c36e251fb405501744363d23935e2d7b8e0da9a4/src/guide/essentials/template-syntax.md?plain=1#L268-L270)的，可以基于这个 fork 了改一个。

**Comment by YFengFly** [comment]
figma 的文件并不在仓库中，有些想不出该如何 fork 并 PR。
先提一个 issue，然后由 figma 源文件所有人修改后再发布？
还是先自己改好后提交文件（比如我修改的这个demo）？
[Diagram - Directive - zh-cn.zip](https://github.com/vuejs-translations/docs-zh-cn/files/10555648/Diagram.-.Directive.-.zh-cn.zip)

**Comment by Justineo** [comment]
Figma 上的内容多人协同可能没办法像代码那样操作，我们先内部讨论一下怎么处理。

**Comment by Jinjiang** [comment]
https://github.com/vuejs/v2.vuejs.org/tree/master/assets

v2 是这样处理的，只是当时用的是 Adobe Illustrator，所以源文件是 `*.ai` 格式。我觉得可以做类似的处理：

1. 首先我们也在 repo 里创建一个 assets 目录，把初始版本的 Figma 文件通过 save local copy 保存到本地放在那里。
2. 大家可以各自想办法把这个文件导入自己的 Figma 上进行编辑，编辑过后同样 save local copy 保存到本地，然后把本地的 `*.fig` 文件提交到 assets 目录，然后发 PR。
3. Review 的同学也可以把该 review 的文件自行上传到自己的 Figma 操作环境进行 review。

大家觉得如何

**Comment by Justineo** [comment]
我觉得可以，先得把上游 repo 改造一下。

**Comment by Jinjiang** [comment]
我仔细想了一下翻译的流程，我们可以这样：

1. 基于原文注释的 figma 链接自己 fork 一份
2. 修改之后导出新的图片
3. 在仓库中添加图片，图片文件名添加 `_zh-cn` 的后缀，同时在中文翻译处添加这份 fork 的 URL (此处同时保留英文和中文的 URL，英文第一个，中文第二个)，该 figma fork 在 URL 提交之后不建议再修改
4. 今后每次更新中文翻译图片的时候，必要的话 fork 可以叠加，且需要更新 fork 的 URL

这样，原版图片的更新消息可以通过原图片文件的更新获得，同时翻译版本的图片和源文件也可以处于健康的维护状态

大家觉得如何？

**Comment by Jinjiang** [comment]
流程更新至 wiki https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5#4-%E5%85%B3%E4%BA%8E%E6%96%87%E6%A1%A3%E4%B8%AD%E7%9A%84%E5%9B%BE%E7%89%87
