### ISSUE TITLE
请问“行为规范”页面为什么是直接外链至原英文文档？

### ISSUE THREAD

**Issue by Gahotx** [vuejs-translations/docs-zh-cn#646]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

在中文文档中直接点击“行为规范”跳转至原英文文档没问题，但如果阅读者是在浏览英文文档的“Code Of Conduct”页面时点击多语言跳转到对应的中文文档链接时，会显示404，体验不太好。
![image](https://user-images.githubusercontent.com/53534938/216554722-97b862a7-aba6-4c21-8a55-4aec8bcf4d3a.png)

**Comment by wxsms** [comment]
早前站点部署在 gitee 的时候，该页面敏感词过多，导致无法部署且无提示。因此暂时使用了外链。

**Comment by Gahotx** [comment]
原来如此，多谢回复。
