### ISSUE TITLE
本地运行项目失败 

### ISSUE THREAD

**Issue by Sunny-117** [vuejs-translations/docs-zh-cn#653]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

网络环境和本地化

### 问题描述

![image](https://user-images.githubusercontent.com/73089592/217458995-6172f3ae-a747-4ce9-9187-82199ec697aa.png)
![image](https://user-images.githubusercontent.com/73089592/217459023-2d481663-0167-4ec9-9554-40eea13c4772.png)

**Comment by Thorne97** [comment]
我也遇到了同样的问题

**Comment by Sunny-117** [comment]
https://github.com/vuejs-translations/docs-zh-cn/pull/659 修复

**Comment by Sunny-117** [comment]
done
