### ISSUE TITLE
[认领][翻译]:src/guide/built-ins/keep-alive.md

### ISSUE THREAD

**Issue by RedLemonPie** [vuejs-translations/docs-zh-cn#66]

**Comment by Matrix53** [comment]
这篇应该已经翻译过了，在[这里](https://github.com/vuejs-translations/docs-zh-cn/blob/main/src/guide/built-ins/keep-alive.md)

**Comment by Jinjiang** [comment]
@RedLemonPie 如楼上所说这篇文档已经翻译过了，确认一下你是要参与校对还是翻译其它文档。
谢谢
