### ISSUE TITLE
页面 https://cn.vuejs.org/about/coc.html 提示404

### ISSUE THREAD

**Issue by Yuiai01** [vuejs-translations/docs-zh-cn#662]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

通过页面 https://github.com/vuejs/core/blob/main/.github/contributing.md 进入 https://vuejs.org/about/coc.html 页面，选择中文，进入 https://cn.vuejs.org/about/coc.html，提示 404 ，截图如下：
<img width="695" alt="image" src="https://user-images.githubusercontent.com/112228030/218711695-526406a7-5fce-4e05-8501-9f0a622be380.png">

**Comment by wxsms** [comment]
pls see #646
