### ISSUE TITLE
路径丢失

### ISSUE THREAD

**Issue by QiuShuiDyp** [vuejs-translations/docs-zh-cn#674]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

[过渡动效](https://v3.router.vuejs.org/zh/guide/advanced/transitions.html#%E5%8D%95%E4%B8%AA%E8%B7%AF%E7%94%B1%E7%9A%84%E8%BF%87%E6%B8%A1)
从下方点击访问url：https://cn.vuejs.org/guide/transitions.html，路径丢失
![image](https://user-images.githubusercontent.com/22740242/223069422-16409ead-a1ac-4be8-831d-404383497c4c.png)

**Comment by wxsms** [comment]
Closed as commit merged.
