### ISSUE TITLE
搜索栏搜索文档v-text点击后会出现下面截图错误

### ISSUE THREAD

**Issue by ruhao123** [vuejs-translations/docs-zh-cn#691]
<img width="1407" alt="截屏2023-03-22 10 38 46" src="https://user-images.githubusercontent.com/52919449/226787734-0bc5c01e-1df5-43d7-9d93-262890fd2d62.png">

**Comment by ruhao123** [comment]
是vue2的文档有这个问题

**Comment by ruhao123** [comment]
<img width="1439" alt="截屏2023-03-22 10 46 13" src="https://user-images.githubusercontent.com/52919449/226788781-9b147379-488a-436f-8413-2b830a6f8f72.png">

**Comment by ruhao123** [comment]
点击以后就会跳转到报错页面

**Comment by veaba** [comment]
没有发现这个问题，麻烦把 url 截图截全下。

v2 可以到这个仓库反馈：https://github.com/vuejs/v2.cn.vuejs.org
