### ISSUE TITLE
插槽-具名插槽template缺少结束标记

### ISSUE THREAD

**Issue by shinaidi** [vuejs-translations/docs-zh-cn#696]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

![image](https://user-images.githubusercontent.com/71696644/229443614-082c7afb-83b9-409b-bb1a-a1f78dc108b3.png)
<template> Element is missing end tag.
https://cn.vuejs.org/guide/components/slots.html#named-slots

**Comment by Jinjiang** [comment]
这应该属于英文版的问题，且如果要改的话所有翻译版本都需要更新，所以建议在原版文档开 issue 讨论
谢谢
