### ISSUE TITLE
theme路径打开是空白内容

### ISSUE THREAD

**Issue by yuzexia** [vuejs-translations/docs-zh-cn#699]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

/resources/themes.html
这个路径

https://cn.vuejs.org/resources/themes.html

页面未找到
你打开了一个不存在的链接：/resources/themes.html。
不介意的话请提交到[这里](https://github.com/vuejs-translations/docs-zh-cn)，我们会跟进修复。

**Comment by wxsms** [comment]
请问你是从哪个页面跳转到这个路径的？

**Comment by yuzexia** [comment]
连接：https://v2.cn.vuejs.org/
右侧资源列表-->主题
