### ISSUE TITLE
Composition API FAQ 中的 gist 在国内无法访问

### ISSUE THREAD

**Issue by Jinjiang** [vuejs-translations/docs-zh-cn#712]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

网络环境和本地化

### 问题描述

https://cn.vuejs.org/guide/extras/composition-api-faq.html#more-flexible-code-organization
中的 gist 地址在国内访问不了https://gist.github.com/yyx990803/8854f8f6a97631576c14b63c8acd8f2e

https://github.com/vuejs/docs/issues/2307

**Comment by censujiang** [comment]
这个就是你的问题。。。

**Comment by sxzz** [comment]
可以考虑换成 raw https://gist.githubusercontent.com/yyx990803/8854f8f6a97631576c14b63c8acd8f2e/raw/ce3572edfc332aa2825f2951a1c97f663d39ae4f/FileExplorer.vue

国内可以访问
<img width="621" alt="image" src="https://github.com/vuejs-translations/docs-zh-cn/assets/6481596/bdaa2d69-9f67-4434-9c45-da768e904e0d">
