### ISSUE TITLE
深入响应式系统ref描述错误

### ISSUE THREAD

**Issue by LeoKun1231** [vuejs-translations/docs-zh-cn#724]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

你好，ref这里表诉应该是错的，getter/setter仅用于ref的基本数据类型，对于引用类型的ref，也是proxy实现的
[image](https://github.com/vuejs-translations/docs-zh-cn/assets/88810970/d06ea2af-9d35-4beb-a64c-3ba61979fea4)

**Comment by Justineo** [comment]
“仅将 getter/setter 用于 ref”不等于“ref 仅基于 getter/setter 实现”，你可以细品一下 😄
