### ISSUE TITLE
component-basics中英文`accessibility `翻译成`A11y`的问题

### ISSUE THREAD

**Issue by higuaifan** [vuejs-translations/docs-zh-cn#734]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

https://github.com/vuejs-translations/docs-zh-cn/blob/14c69cda3762603333375e7e37633be4e9a1f13d/src/guide/essentials/component-basics.md?plain=1#L306

此处的`A11y`使用"无障碍“会不会更加友好一点？`accessibility`似乎是与`vue`无关的额外的单词。

**Comment by Jinjiang** [comment]
认同，这里翻译成“无障碍访问”比较好
