### ISSUE TITLE
建议：去除指向 MDN 文档链接的 locale 部分（除非文档指向特定小节）

### ISSUE THREAD

**Issue by yin1999** [vuejs-translations/docs-zh-cn#753]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

网络环境和本地化

### 问题描述

目前，Vue.js 文档中指向 MDN 的文档的链接使用了 `en-US` locale，而未使用本地化的链接。当然，直接粗暴地将这些 en-US 改为 zh-CN 也存在部分中文文档不存在，而页面不会直接跳转到英文文档的问题（会先显示一个文档不存在的页面，并提示用户可以跳转到英文文档），但如果是指向英文文档，后面文档被翻译时，又需要重新更新链接，增加了维护文档的工作量。目前 MDN 的项目采用的做法是，去除链接中的 locale 部分，那服务器会根据用户的选择，自动跳转到适合当前用户选择的语言环境的文档（参见我们在 [BCD（浏览器兼容性数据）项目中的写法](https://github.com/mdn/browser-compat-data/blob/c0dac88aaefe245ff0cdbbb9f021e94154e96de5/api/AbortController.json#L5)）。

这也是 vs code 中应用 MDN 链接的方法：

![image](https://github.com/vuejs-translations/docs-zh-cn/assets/15844309/48fd3e7d-daba-4529-961f-3bcd7e2cbc0f)

需要注意的是，有些指向 MDN 的链接是链接到特定小节的，这些链接可能只能直接使用本地化的链接。

**Comment by Justineo** [comment]
目前有遇到中文文档不存在的情况么？如果没有的话我理解暂时不用动。Vue.js 指向 MDN 的部分一般不会是一些特别新的或者小众的 API，我理解不太容易出现你所说的这个现象。我觉得我们可以在遇到缺失翻译的情况再去调整。

**Comment by yin1999** [comment]
> 目前有遇到中文文档不存在的情况么？如果没有的话我理解暂时不用动。Vue.js 指向 MDN 的部分一般不会是一些特别新的或者小众的 API，我理解不太容易出现你所说的这个现象。我觉得我们可以在遇到缺失翻译的情况再去调整。

也有一部分中文文档（不是特别新的 API）我们是还未翻译的，根据我现在的统计，MDN 中文文档只翻译了英文文档中大概一半的文档：

![image](https://github.com/vuejs-translations/docs-zh-cn/assets/15844309/22efc4fe-0b88-4ce9-88cc-237e1c758f06)

如果暂时不按此建议更新，也建议指向简体中文的 MDN 文档（需要一个一个检查是否存在中文文档，我相信大部分用到的文档都应该是有中文的，不排除一部分文档仍未被本地化）。

**Comment by Jinjiang** [comment]
如果这个链接是可靠的我觉得可以试试看。我们不妨把这个话题拿到英文站多讨论一下？如果这样真得行得通，我们从根源上解决这个问题好了，别的语言的翻译可能也会受益。 @yin1999

**Comment by Justineo** [comment]
我本机测试的结果是本地化链接调到了 en-US 版本（在 zh-CN 版本存在的情况下），不确定 MDN 现在自动判断的逻辑是什么。（我用的中文系统 & 中文版 Chrome）

**Comment by yin1999** [comment]
逻辑大概是这样的，MDN 的服务器会优先跳转到你之前访问 MDN 页面时选择的语言区域（cookie 中有一个 `preferredlocale`，发送 cookie 到服务器时，如果没有指定语言区域，默认会跳转到该 cookie 指定的语言区域）。如果没有指定这个 cookie（例如第一次访问，则会使用浏览器默认发送的 `Accept-Language` 标头进行判断）。

可参照 mdn/yari 中的相关代码，我在下面贴出几处关键的代码：

- 缺少 locale 部分时的重定向处理入口：https://github.com/mdn/yari/blob/99aeb77091a7913ea4bcab67a365376847415d29/cloud-function/src/middlewares/redirect-locale.ts#L24-L30
- 选择合适的 locale：https://github.com/mdn/yari/blob/99aeb77091a7913ea4bcab67a365376847415d29/libs/locale-utils/index.js#L57-L77

**Comment by Jinjiang** [comment]
@yin1999 由于长期没有新的讨论和结论，这个 issue 我关掉了，如有后续欢迎在英文版讨论，谢谢
