### ISSUE TITLE
To access refs in a component's template  翻译不准确

### ISSUE THREAD

**Issue by qinglangee** [vuejs-translations/docs-zh-cn#757]
### 提问须知

- [x] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

https://vuejs.org/guide/essentials/reactivity-fundamentals.html#ref  

> To access refs in a component's template, declare and return them from a component's setup() function: 

文档翻译成
https://cn.vuejs.org/guide/essentials/reactivity-fundamentals.html#ref  

> 要访问组件模板中的 ref，请从组件的 setup() 函数中声明并返回它们： 

是不是可以改成 `要在组件模板中访问 ref，请从组件的 setup() 函数中声明并返回它们：`

**Comment by wxsms** [comment]
欢迎 PR
