### ISSUE TITLE
v2 链接重定向问题 (内置过渡动画- transition 组件文档 ，点击不可用)

### ISSUE THREAD

**Issue by zdddf** [vuejs-translations/docs-zh-cn#767]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

![image](https://github.com/vuejs-translations/docs-zh-cn/assets/144667012/6adc4341-27cf-435f-b3df-22e3001f313f)
![image](https://github.com/vuejs-translations/docs-zh-cn/assets/144667012/2bac7574-5ed3-473b-82d2-2bd5fe96b58d)

**Comment by wxsms** [comment]
这个链接位于 element ui 的网站上，你应该向 element ui 发起 issue。谢谢。

**Comment by Justineo** [comment]
文档应该是做了 V2 路径的重定向的，似乎是 `vercel.json` 配置的 `redirect` 规则没有覆盖 `/` 结尾的 URL。

**Comment by veaba** [comment]
```json
  "redirects": [
  // 辅助这层可以吗？
    {
      "source": "/v2/:path*/",
      "destination": "https://v2.cn.vuejs.org/v2/:path*/"
    },
   {
      "source": "/v2/:path*",
      "destination": "https://v2.cn.vuejs.org/v2/:path*"
    }
  ]
```

**Comment by Jinjiang** [comment]
恩，我觉得可以对应之前 _redirects 的规则加上看看

**Comment by LT877677447** [comment]
现在好像仍然不行

**Comment by Jinjiang** [comment]
![image](https://github.com/vuejs-translations/docs-zh-cn/assets/206848/9af68fca-a409-44bd-afe7-e75fc0960704)
应该是 v2 文档站的配置问题，导致链接跳过去又跳回来了。本身这边的 redirects 配置应该已经生效了

**Comment by Jinjiang** [comment]
更新：我发现有个 301 跳转导致 vercel.json 里的 redirects 规则没有被作用在这个链接上，待进一步排查
![image](https://github.com/vuejs-translations/docs-zh-cn/assets/206848/29e1916f-12f2-4410-b740-13b87579fbe2)

**Comment by slince-zero** [comment]
有相同的问题，
![image](https://github.com/vuejs-translations/docs-zh-cn/assets/40690276/42063875-21b2-424d-acec-9963175f0609)

**Comment by Jinjiang** [comment]
更新：目前 https://cn.vuejs.org/v2/api/ 及其他 `/v2/*` 开头的 URL 已经可以跳转至 v2 文档
