### ISSUE TITLE
cn.vuejs.org无法访问

### ISSUE THREAD

**Issue by zzs89117920** [vuejs-translations/docs-zh-cn#769]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

网络环境和本地化

### 问题描述

cn.vuejs.org无法访问
![image](https://github.com/vuejs-translations/docs-zh-cn/assets/5515847/832723dc-17ff-4341-82f5-c13bd7631760)

**Comment by yyx990803** [comment]
调整了一下 cdn 设置，现在应该国内大部分地区都可以正常访问了，有些地区可能滞后。如有问题请开新 issue

**Comment by JUST-Limbo** [comment]
> 调整了一下 cdn 设置，现在应该国内大部分地区都可以正常访问了，有些地区可能滞后。如有问题请开新 issue

帅哥，有些Ip还是打不开。

归属地： 
中国 上海市 浦东新区
运营商：
中国联通
本机IP：
223.167.47.***

**Comment by JUST-Limbo** [comment]
你是不是联通，上海浦东新区联通目前还存在这个问题，刚打电话给10010让他们排查。
