### ISSUE TITLE
/guide/components/events.html 链接不存在

### ISSUE THREAD

**Issue by gengkaihui** [vuejs-translations/docs-zh-cn#772]
点击” 深入组件-**[事件](https://cn.vuejs.org/guide/components/events.html)** “跳转后提示链接不存在

**Comment by gengkaihui** [comment]
很奇怪，直接点击该issue 的链接是可以正常跳转的，如果是在文档中直接点击，则提示错误
![Snipaste_2023-10-10_15-02-56](https://github.com/vuejs-translations/docs-zh-cn/assets/32035860/096e93ab-64ac-429e-8c46-4832fd6ea459)

**Comment by Jinjiang** [comment]
我们并没有发现类似的情况，估计是网络或本地环境之类的问题
