### ISSUE TITLE
点击列表渲染这一章节时 出现页面未找到

### ISSUE THREAD

**Issue by Vayne-bit** [vuejs-translations/docs-zh-cn#791]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

![QQ截图20231129181145](https://github.com/vuejs-translations/docs-zh-cn/assets/69096301/f6717944-2d8c-4259-9387-feb6936958c1)
![QQ截图20231129181153](https://github.com/vuejs-translations/docs-zh-cn/assets/69096301/e03bd3d5-c1af-425f-9713-3bcbb1b3882d)

**Comment by Justineo** [comment]
无法复现，请再确认一下复现路径。

**Comment by Vayne-bit** [comment]
> 无法复现，请再确认一下复现路径。

谢谢您回答我的问题
我重新清空了浏览器缓存试了，发现可以了，可能是我的浏览器缓存问题，
