### ISSUE TITLE
集中翻译和校对工作汇总

### ISSUE THREAD

**Issue by Jinjiang** [vuejs-translations/docs-zh-cn#8]
大家好，这里是最新版的 Vue 中文文档站 (staging 中)，有大量的文档有待集中翻译和校对，也希望可以得到社区的大力支持！

所以我们创建了这个 issue 来汇总这些工作。

### 首先介绍一下目前文档站的状态

1. 我们按照页面为颗粒度将所有需要翻译和校对的页面统计在了 GitHub project board：
    - ~~Guide: https://github.com/vuejs-translations/docs-zh-cn/projects/1~~ (已完成)
    - ~~API: https://github.com/vuejs-translations/docs-zh-cn/projects/2~~ (已完成)
    - ~~Tutorial: https://github.com/orgs/vuejs-translations/projects/1~~ (已完成)
    - Examples: https://github.com/orgs/vuejs-translations/projects/2
3. 每个页面理论上都需要经历“未认领 (默认)”、“已认领”、“待校对”、“已完成”四个状态。

### 如何参与本次集中翻译和校对

**注意：~~通常我们只处理英文版中已经稳定的页面，目前已经稳定的部分只有 `src/guide` 目录下的页面，英文版的文档也在集中撰写中，后续会陆续增加稳定的页面~~。目前所有页面均已稳定，可以进行翻译和校对。**

目前的页面有两类状态，一类是英文版，尚未翻译，另一类是已经翻译但是并未有其他人校对。

- 对于尚未翻译的内容
  1. 创建一则新的 issue 认领翻译，我们看到之后会整理到 project board (关联到 project 并设置为"已认领")
  2. 翻译完毕后，提交并创建 PR，我们看到之后整理到 project board (关联到之前创建的 issue 并切换状态到"待校对")
  4. 超过社区 2 人或有 Vue 团队成员校对并 approve 之后，我们合并分支并整理到 project board (切换状态到"已完成")
  5. 该 issue 自动关闭

- 对于之前已经个人翻译但尚未校对的内容
  1. 创建一则新的 issue 认领校对，我们看到之后会整理到 project board (关联到 project 并设置为“已认领”)
  2. 校对完毕后，提交修改意见并创建 PR，我们看到之后整理到 project board (关联到之前创建的 issue 并切换状态到"待校对")
  3. Vue 团队成员进行校对和合并分支，并整理到 project board (切换状态到“已完成”)
  4. 该 issue 自动关闭

_注意：可以重复校对，但我们会尽量回避大家重复翻译和过度集中校对某一篇文档，所以建议大家参与之前来这里认领一下以避免其他人重复翻译或过度校对。_

### 其它注意事项

详见 [wiki](https://github.com/vuejs-translations/docs-zh-cn/wiki)

_如果大家有兴趣参与翻译和校对，欢迎创建 issue 认领相关工作！_

谢谢

**Comment by MarvinXu** [comment]
昨天刚加入翻译，暂时有两点建议：
- project 看板里的“翻译”和“校对”状态分开。比如未认领的翻译和校对混在了一起，难以区分哪些是“待翻译”、哪些是“已翻译待校对”的。而且我领了一篇翻译不太完整的文章准备校对，也不知道原作者是不是还在继续翻译。
- 有没有 TG 或 Discord 讨论组，有些翻译细节想讨论但又没到整理好发成 issue 的程度...

**Comment by wxsms** [comment]
> project 看板里的“翻译”和“校对”状态分开。比如未认领的翻译和校对混在了一起，难以区分哪些是“待翻译”、哪些是“已翻译待校对”的。而且我领了一篇翻译不太完整的文章准备校对，也不知道原作者是不是还在继续翻译。

@MarvinXu 感谢贡献，如果没有在 issue 列表中找到认领记录，那么应该可以认为是没有在继续翻译中的。至于 project board 的提问，可能要请其它成员来回答一下。

> 有没有 TG 或 Discord 讨论组，有些翻译细节想讨论但又没到整理好发成 issue 的程度...

目前据我所知没有这些讨论组，欢迎到 https://github.com/vuejs-translations/docs-zh-cn/discussions 发起讨论。

> 我fork后参考README.md pnpm i 和 pnpm run dev失败，发现node版本是12的，切换到node V16才可以运行，是否应该在README.md加上node 版本

@web-wgf 我觉得没问题，欢迎贡献。

**Comment by Jinjiang** [comment]
> 我fork后参考README.md `pnpm i` 和 `pnpm run dev`失败，发现node版本是12的，切换到node V16才可以运行，是否应该在README.md加上node 版本

这个我来快速核实一下，如果运行会失败确实应该注明一下

**Comment by Jinjiang** [comment]
> 有没有 TG 或 Discord 讨论组，有些翻译细节想讨论但又没到整理好发成 issue 的程度...

我们专门有翻译讨论的 issue 类型，个人感觉没有什么不可以发成 issue 讨论的，即便是一些很小的细节。

https://github.com/vuejs-translations/docs-zh-cn/issues?q=is%3Aissue+label%3A%E7%BF%BB%E8%AF%91%E8%AE%A8%E8%AE%BA+

**Comment by jCodeLife** [comment]
你好，对于二次校对是否也需要创建一则新的 issue 认领校对，还是说直接提pr呢？

**Comment by Jinjiang** [comment]
跟大家更新一下进度：目前 guide 部分算是全部翻译+校对至少一遍了，接下来我们的主要工作会放在 API 的部分上。谢谢

**Comment by Jinjiang** [comment]
跟大家更新一下进度：目前 API 部分已经全部被认领且接近完成了，接下来我们集中翻译 tutorial 和 examples 的部分上，这也是我们正式发布前的最后两个部分了。欢迎大家认领和支持。谢谢

**Comment by Jinjiang** [comment]
跟诸位更新一下，目前主体中文内容 (指南、API、范例、教程) 已经全部翻译+校对完毕。稍后我们会进行最后的收尾工作并正式发布上线。非常感谢大家的支持！

网站此后也会由集中翻译与校对转为定期从英文版更新同步的模式。
