### ISSUE TITLE
测试指南打不开

### ISSUE THREAD

**Issue by ruo-an-an** [vuejs-translations/docs-zh-cn#803]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

![Snipaste_2023-12-20_15-37-32](https://github.com/vuejs-translations/docs-zh-cn/assets/121413920/4cb1e2df-4b29-4aa1-8b2c-5b46e8f4c6d3)
![Snipaste_2023-12-20_15-37-19](https://github.com/vuejs-translations/docs-zh-cn/assets/121413920/2ed58f96-70f4-4ac4-9378-a54ad8f813cd)

**Comment by KiritaniAyaka** [comment]
咱这边无法复现，可能是缓存导致的，可以刷新页面试试

**Comment by veaba** [comment]
Ctrl + F5 强刷下资源，大概是好久没访问 CDN 缓存了。
