### ISSUE TITLE
Firefox 121.0 访问Vue3官方简体中文教程 基础-模板语法 页面失效

### ISSUE THREAD

**Issue by Teruha** [vuejs-translations/docs-zh-cn#826]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

网络环境和本地化

### 问题描述

Firefox 121.0 (64 位)访问
https://cn.vuejs.org/guide/essentials/template-syntax.html
时出现，Chrome访问正常：

![image](https://github.com/vuejs-translations/docs-zh-cn/assets/15813042/734a0454-57cc-447b-899e-66d64310710c)

**Comment by veaba** [comment]
Ctrl + F5 强刷下资源，大概是好久没访问 CDN 缓存了。
