### ISSUE TITLE
侧边广告位显示问题

### ISSUE THREAD

**Issue by songyipan** [vuejs-translations/docs-zh-cn#835]
### 提问须知

- [x] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [x] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [x] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 当我点击关闭按钮
![image](https://github.com/vuejs-translations/docs-zh-cn/assets/65063252/55cd917a-6048-476e-b65c-66dd073dfd9e)
### 这个地方还是有显示
![image](https://github.com/vuejs-translations/docs-zh-cn/assets/65063252/41ab5864-c4e1-411a-bc5f-e827f529f37a)
### 我想提交一个pr但是没有相关代码
![image](https://github.com/vuejs-translations/docs-zh-cn/assets/65063252/96f1a44c-082c-4600-8a95-699a3911759c)
请问是我找的地方不对还是本来就是没有这段代码，我好想提交一个pr

**Comment by huyikai** [comment]
可以试试这样
``` vue
<script setup lang="ts">
import { onMounted, nextTick } from 'vue'
onMounted(async () => {
  const s = document.createElement('script')
  s.async = true
  s.src = `https://cdn.wwads.cn/js/makemoney.js`
  document.querySelector('.wwads-container')!.appendChild(s)
  await nextTick();
  document.addEventListener('click', function(e) {
    if ((e.target as HTMLElement).classList.contains('wwads-hide')) {
      const wwadsContainer = document.querySelector('.wwads-container');
      if (wwadsContainer) {
        wwadsContainer.remove();
      }
    }
  });
})
</script>
```

**Comment by Jinjiang** [comment]
体验了一下，感觉不影响正常使用，必要性不大了，暂不做处理
谢谢反馈
