### ISSUE TITLE
vue3文档，左侧导航，动画技巧 点击跳转显示404

### ISSUE THREAD

**Issue by liujing-1993** [vuejs-translations/docs-zh-cn#854]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

![11111](https://github.com/vuejs-translations/docs-zh-cn/assets/31032987/3d4904a1-cb63-447e-9e32-f62e94471480)

rt

**Comment by huyikai** [comment]
没有复现出描述的问题。
![image](https://github.com/vuejs-translations/docs-zh-cn/assets/25839948/918a6afb-0589-4152-a48c-dd3ade0d5e65)

**Comment by veaba** [comment]
Ctrl + F5 强刷下资源，大概是好久没访问 CDN 缓存了。
