### ISSUE TITLE
代码demo希望能区分setup具体两种语法

### ISSUE THREAD

**Issue by github-cherry** [vuejs-translations/docs-zh-cn#862]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

希望能全局配置语法的阅读习惯，比如现有的[api风格](https://cn.vuejs.org/guide/introduction.html#api-styles)可配。那么希望[Composition API](https://cn.vuejs.org/guide/introduction.html#composition-api)也可以再具体配置阅读习惯，选择setup语法糖还是setup函数的方式浏览文档。
如果选了setup语法糖，那么整个文档的代码demo都是语法糖的风格。如果选了setup函数的方式，那么整个文档的代码demo就是setup函数的语法展示

**Comment by Justineo** [comment]
这个项目仅处理和翻译相关的问题，这个建议需要发到英文文档所在项目。
