### ISSUE TITLE
部分导航页面点击无法访问，提示未找到

### ISSUE THREAD

**Issue by seechangan** [vuejs-translations/docs-zh-cn#869]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

![image](https://github.com/vuejs-translations/docs-zh-cn/assets/31404297/bd6e6dd7-5082-4258-8a31-f27fbff2da92)
![image](https://github.com/vuejs-translations/docs-zh-cn/assets/31404297/dc5d9a2b-0937-49a9-b6ca-9e9ee2dd3ab8)
 图二种红线标记出来的跳转页面。 都与图1的结果一样， 无法访问。

https://cn.vuejs.org/about/faq.html

**Comment by veaba** [comment]
Ctrl + F5 强刷下资源，大概是好久没访问 CDN 缓存了。
