### ISSUE TITLE
[认领][校对]:src\guide\essentials\computed.md

### ISSUE THREAD

**Issue by web-wgf** [vuejs-translations/docs-zh-cn#87]
![image](https://user-images.githubusercontent.com/69149369/153980830-5a3c7868-c79e-4985-80a5-6c35359186bf.png)

![image](https://user-images.githubusercontent.com/69149369/153980733-deb5e29b-ef19-4178-956e-f8bf05486ed3.png)

**Comment by wxsms** [comment]
你好，请注意更新一下代码以避免重复劳动。因为你提到的这个点有其它同学的 PR 已经覆盖到了，并且刚刚并入。谢谢。

**Comment by web-wgf** [comment]
好的
