### ISSUE TITLE
文档版本问题

### ISSUE THREAD

**Issue by zhangsd** [vuejs-translations/docs-zh-cn#879]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

文档的版本怎么回滚了 v3.4版本的内容都没了

**Comment by Justineo** [comment]
无法复现，比如这里的就是正常的：

https://cn.vuejs.org/guide/essentials/template-syntax.html#same-name-shorthand

**Comment by zhangsd** [comment]
https://cn.vuejs.org/guide/components/v-model.html
文档里关于defineModel的内容都没了

**Comment by zhangsd** [comment]
> 无法复现，比如这里的就是正常的：
> 
> https://cn.vuejs.org/guide/essentials/template-syntax.html#same-name-shorthand

https://cn.vuejs.org/guide/components/v-model.html
文档里关于defineModel的内容都没了

**Comment by Justineo** [comment]
<img width="1177" alt="image" src="https://github.com/vuejs-translations/docs-zh-cn/assets/1726061/ea22e50e-ca9e-42f5-a1bd-7acc85230bb1">

清下缓存看看？

**Comment by zhangsd** [comment]
> <img alt="image" width="1177" src="https://private-user-images.githubusercontent.com/1726061/311605281-ea22e50e-ca9e-42f5-a1bd-7acc85230bb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNDk1NTUsIm5iZiI6MTcxMDE0OTI1NSwicGF0aCI6Ii8xNzI2MDYxLzMxMTYwNTI4MS1lYTIyZTUwZS1jYTllLTQyZjUtYTFiZC03YWNjODUyMzBiYjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTFUMDkyNzM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWQzNWQyNWI2YTk1ODUyODMwNjU1ODJjMGQxZDQxMjY4NjJjOWM2MTE5OWI5NzM5ZDYxYjZiYzZjMmYzY2M0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Upj7OyR236FTl74SZE92IIr74Q0DVPiA99C0dKujkN8">
> 清下缓存看看？

tks  感觉是cdn不稳定（经常有js 404） 
这个问题是一个js加载失败，导致api风格默认选择了Options
