### ISSUE TITLE
文档访问资源缺失

### ISSUE THREAD

**Issue by HodgeWen** [vuejs-translations/docs-zh-cn#881]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

- 中文文档部署有问题首页样式无法加载，部分链接无法跳转。
- 打开控制台后可以发现部分资源文件404

[链接地址](https://cn.vuejs.org/guide/introduction.html)

![image](https://github.com/vuejs-translations/docs-zh-cn/assets/30290407/58ea2c31-b29a-4bf0-b2f9-0d777685d844)

![image](https://github.com/vuejs-translations/docs-zh-cn/assets/30290407/0f058235-c349-45e8-b3b2-23950336fb13)

**Comment by dongnaebi** [comment]
![image](https://github.com/vuejs-translations/docs-zh-cn/assets/6902417/44007901-40d1-4325-848e-43fac851a9d3)

我的情况

**Comment by jonezhan** [comment]
![image](https://github.com/vuejs-translations/docs-zh-cn/assets/99855905/080751a0-3f2a-496b-997f-44efd334f3b2)
官网崩了

**Comment by awxiaoxian2020** [comment]
似乎现在是正常的。

**Comment by sxzz** [comment]
之前因为 Cloudflare CDN 缓存抽风，导致部分地区可能存在 404 的情况。目前已经解决，大部分地区应该已经可以访问。如仍遇问题，尝试清除浏览器与 DNS 缓存。或尝试开启/关闭 VPN 服务。


<img width="639" alt="image" src="https://github.com/vuejs-translations/docs-zh-cn/assets/6481596/1ed29bc9-54be-45ed-8d62-bce17d8bbd6b">
