### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by skywangch** [vuejs-translations/docs-zh-cn#883]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

![image](https://github.com/vuejs-translations/docs-zh-cn/assets/28942093/61dbe37d-0b79-4ea5-86c0-ad1cfe532dc6)

中文原文：因此这次作用也可以说是一个它依赖的订阅者 (subscriber)。
英文原文：The effect is said to be a subscriber to its dependencies.

问题：“它”和“订阅者”指代的都是“作用”，这里“它依赖的订阅者”逻辑混乱

建议修改为：因此这次作用也可以被称作它的依赖的一个订阅者 (subscriber)

中文地址：https://cn.vuejs.org/guide/extras/reactivity-in-depth.html#how-reactivity-works-in-vue
英文地址：https://vuejs.org/guide/extras/reactivity-in-depth.html#how-reactivity-works-in-vue

**Comment by wangjue666** [comment]
当前翻译的确有些拗口，你提议的读起来顺畅一些。已提PR
