### ISSUE TITLE
中文官网样式错乱了

### ISSUE THREAD

**Issue by linghuam** [vuejs-translations/docs-zh-cn#885]
### 提问须知

- [x] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

网络环境和本地化

### 问题描述

访问站点：https://cn.vuejs.org/
出现问题：
![image](https://github.com/vuejs-translations/docs-zh-cn/assets/14136287/e4f5495c-54a6-45c7-89b3-77b071ae138b)

**Comment by seachenjy** [comment]
assets目录下的文件404了，网站显示不正常

**Comment by sxzz** [comment]
Duplicate of #881

**Comment by Botrance** [comment]
在手机上是我目前是正常的，电脑是错版的

**Comment by sxzz** [comment]
See https://github.com/vuejs-translations/docs-zh-cn/issues/881

**Comment by veaba** [comment]
现在观察到网站已恢复，感谢参与~
