### ISSUE TITLE
中文样式问题解决方案

### ISSUE THREAD

**Issue by jonezhan** [vuejs-translations/docs-zh-cn#886]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [ ] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [ ] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

按图片设置，刷新一下页面就行了
![Snipaste_2024-03-13_14-50-01](https://github.com/vuejs-translations/docs-zh-cn/assets/99855905/7d80c34d-a66f-407c-8dc2-4df5623d72f9)

**Comment by veaba** [comment]
网站已恢复，感谢提供方案~
