### ISSUE TITLE
组件基础这一页无法正确访问和链接

### ISSUE THREAD

**Issue by landall** [vuejs-translations/docs-zh-cn#892]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

https://cn.vuejs.org/guide/essentials/component-basics.html
该页面英文版可访问，中文版无法访问。
从菜单进入时，和从模版引用这一页进入时，会进入模版引用那一页。

**Comment by Justineo** [comment]
无法复现，请尝试一下清除浏览器缓存后重新访问。

**Comment by landall** [comment]
我在邮箱app里能直接点进去，应该是我自己的safari这边出了啥奇怪的问题了。
这之前的页面都能访问，从这页开始之后的都不能。
如果后续还有规律地出现的话，我再来重新提issue吧。
我盲猜是某个错误的cookie导致服务器端502了。
