### ISSUE TITLE
首页安装按钮跳转 404

### ISSUE THREAD

**Issue by lxfljw** [vuejs-translations/docs-zh-cn#893]
安装页面404 https://cn.vuejs.org/guide/quick-start.html

![image](https://github.com/vuejs-translations/docs-zh-cn/assets/30398355/a3a8d01a-e2aa-4fc5-8395-763b523c8eca)
![image](https://github.com/vuejs-translations/docs-zh-cn/assets/30398355/3dd41ff6-e942-485b-a098-b94531cef76f)

**Comment by veaba** [comment]
Ctrl + F5 强刷下资源，大概是好久没访问 CDN 缓存了。
