### ISSUE TITLE
Vue 这个名字还是不要翻译了

### ISSUE THREAD

**Issue by sunheyi6** [vuejs-translations/docs-zh-cn#895]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

翻译为这个真的不合适，保留 vue 这个单词原文吧
![image](https://github.com/vuejs-translations/docs-zh-cn/assets/50973219/5e52ca2e-5b9e-4f96-b96b-ba81ae51e78e)

**Comment by Chilfish** [comment]
只是愚人节限定🤣 86486bb

**Comment by Aurorxa** [comment]
额，这也可以

**Comment by sunheyi6** [comment]
> 只是愚人节限定🤣 [86486bb](https://github.com/vuejs-translations/docs-zh-cn/commit/86486bb37e746cb922b7dc46c19730797b028065)
> 
> > https://twitter.com/zhaojinjiang/status/1774590282618786115

都没想到是愚人节 我淦
