### ISSUE TITLE
页面未找到：链接：/guide/scaling-up/ssr.html 不存在

### ISSUE THREAD

**Issue by gengkaihui** [vuejs-translations/docs-zh-cn#900]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

页面找不到 https://cn.vuejs.org/guide/scaling-up/ssr.html
<img width="660" alt="Snipaste_2024-04-04_19-38-27" src="https://github.com/vuejs-translations/docs-zh-cn/assets/32035860/b7f03e17-0297-4c8f-9919-7c3e90b1912d">

**Comment by veaba** [comment]
CTRL + F5，重新刷新你的浏览器缓存。

**Comment by xiaowangxiaowang256256** [comment]
> CTRL + F5，重新刷新你的浏览器缓存。

好的，重新刷新后，当前页面已恢复正常
