### ISSUE TITLE
显示异常：赞助商信息无法正常显示

### ISSUE THREAD

**Issue by xiaowangxiaowang256256** [vuejs-translations/docs-zh-cn#901]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

网络环境和本地化

### 问题描述

1、当前网站，箭头指示部分，显示功能异常
![a631083b19ca34d52688883dbed09a1](https://github.com/vuejs-translations/docs-zh-cn/assets/111274524/a4ce240f-7fb1-402e-b95d-e847d4e36922)
2、拉取github 仓库代码后，本地运行未出现该错误
![image](https://github.com/vuejs-translations/docs-zh-cn/assets/111274524/3c9ac811-7c4a-47d3-8c13-e97590d4b522)
3、个人认为，可能与5天前的 这部分的代码推送有关
![image](https://github.com/vuejs-translations/docs-zh-cn/assets/111274524/1d75dbcf-9bf3-40ad-86ad-c6885ac2eec8)

**Comment by xiaowangxiaowang256256** [comment]
实况展示
![77](https://github.com/vuejs-translations/docs-zh-cn/assets/111274524/8ccc2379-8a41-4556-80e7-3e0f2e59b50b)

**Comment by veaba** [comment]
CF 日常抽风，禁用缓存，重刷下应该可以的。

![image](https://github.com/vuejs-translations/docs-zh-cn/assets/8652596/eb1873c9-07b5-4a63-bd3b-5abb290a8cb9)

参考 #881 描述，目前暂无更好的办法。
