### ISSUE TITLE
中文官网部分资源404错误导致的功能失效问题

### ISSUE THREAD

**Issue by wuguichiroumeiyou** [vuejs-translations/docs-zh-cn#919]
### 提问须知

- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

网络环境和本地化

### 问题描述

![image](https://github.com/vuejs-translations/docs-zh-cn/assets/26672927/5fe6f089-1903-4b58-ab1a-e701dc6aeb88)

部分js文件404错误了，导致一些功能失效
比如 ctrl+k、明暗切换、目录导航等
访问其他语言的翻译链接都正常，只有简体中文有问题

**Comment by xiaodong2008** [comment]
清理一下缓存，部署没有问题

**Comment by wuguichiroumeiyou** [comment]
清缓存试了没有用

不过我直接访问这5个报错的链接，让浏览器自动缓存下来以后，页面就正常了，也算是一种解决方案
访问这5个js的时候，浏览器经常会把它当页面解析，是不是这个地方产生的问题

![image](https://github.com/vuejs-translations/docs-zh-cn/assets/26672927/b61c1227-0209-4b1d-a103-9b255a97997e)

我也去其他地方提issue问了，说是中国这边网络限制什么的，没办法完美解决
但是我在本地访问其他7种语言的翻译都功能正常，只有中文有问题
所以我感觉不像是解决不了的，应该还是部署的时候什么地方没配置对吧

**Comment by wuguichiroumeiyou** [comment]
这两天看又好了，不知道是问题仍然存在但时好时坏还是偷偷修复了

**Comment by bayesss** [comment]
> 清理一下缓存，部署没有问题

好像跟最新版的chrome有关，我今天chrome自动升级了之后也出现这个问题，safari没问题，chrome升级前也没有问题。

**Comment by shilohooo** [comment]
有啥新消息么~

**Comment by POKEZHANG** [comment]
我之前也遇到这个问题了，最近两天好了

**Comment by SK-Luffa** [comment]
是的，我也遇到这个问题了，本质是由于某些文件404 导致的错误，你可以点击请求链接进去，然后刷新一下知道能正常请求，然后将所有错误请求的链接按照上面的步骤恢复一下，
![image](https://github.com/vuejs-translations/docs-zh-cn/assets/52227746/db02a9bd-b7a5-46ad-b8a0-eefc6c3f3441)

**Comment by veaba** [comment]
cloudflare 在国内部分节点仍然不太稳定，可以CTRL+ F5 强刷新。
如仍然存在，那就继续反复操作，暂无更好的办法了。

**Comment by Jinjiang** [comment]
统一回复一下，首先我们确实发现主站最近出现了在国内访问不稳定的情况，对由此带来的不便深表歉意 🙏 

我们近期也在做一些相关的信息收集和调研，但没有立刻切换别的部署方式，是因为根据经验每家 CDN 都时好时坏，包括之前也跟国内的一些服务合作过，也是说没就没了。非常遗憾。

我个人建议大家暂时通过以下两个网址试试看：
- https://vue-docs-zh-cn.netlify.app/
- https://vue-docs-zh-cn.vercel.app/

如果有更加长期稳定的选择，我们都会考虑，并跟大家保持信息同步。

谢谢
