### ISSUE TITLE
是否有必要Cherry Pick上游的二次元彩蛋

### ISSUE THREAD

**Issue by LaoshuBaby** [vuejs-translations/docs-zh-cn#929]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

先前，Evan You 在上游文档仓库中提交了这样一个 commit：https://github.com/vuejs/docs/commit/b137c7ae7bf9a7f8d79842cb2be22dff058fc809

功能是当[带有有效的uwu参数访问页面](https://ja.vuejs.org/?uwu=Vue.js%E4%B9%9F%E6%83%B3%E8%A6%81%E5%8F%98%E5%BE%97%E5%8F%AF%E7%88%B1)的时候，会展示一个由 [:icarus.gk](https://twitter.com/icarusgkx) 设计的LOGO

（请注意，这不是[Sawaratsuki的版本](https://github.com/SAWARATSUKI/ServiceLogos/blob/main/Vue/Vue.png)）

目前日语版译文已经跟进：https://github.com/vuejs-translations/docs-ja/pull/2040

![Vue.js也想要变得可爱](https://github.com/vuejs-translations/docs-zh-cn/assets/42690037/b04a2f4b-d0c5-4491-a38c-9f2c515d9508)

（或许和  #895 与 #896 中的 “威优易” 有相同量级的争议）

**Comment by wxsms** [comment]
中文仓库一般是做全量同步，如无特殊原因不会单独针对某个内容做处理

**Comment by xiaodong2008** [comment]
上次愚人节的commit引起了挺大争议的，所以后面大概率不会单独针对彩蛋进行特殊处理，正如 @wxsms 所说
