### ISSUE TITLE
网站css文件无法加载，导致页面样式无法正确显示

### ISSUE THREAD

**Issue by luguosong** [vuejs-translations/docs-zh-cn#935]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

网络环境和本地化

### 问题描述

introduction:1 Refused to apply style from 'https://cn.vuejs.org/assets/style.B8In5CQw.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

![image](https://github.com/vuejs-translations/docs-zh-cn/assets/51075143/096cb1ff-1c89-4196-a4cf-eab5a210f162)

**Comment by pangujs** [comment]
干嘛关了，还是这样啊

**Comment by xiaodong2008** [comment]
> 干嘛关了，还是这样啊

请参考 https://github.com/vuejs-translations/docs-zh-cn/issues/919#issuecomment-2087945070 的回答

部署并不存在问题
