### ISSUE TITLE
[认领][校对]: src/guide/components/provide-inject.md

### ISSUE THREAD

**Issue by web-wgf** [vuejs-translations/docs-zh-cn#94]

**Comment by web-wgf** [comment]
TODO: translation

**Comment by GongMingCai** [comment]
已经有人翻译了
https://github.com/vuejs-translations/docs-zh-cn/blob/main/src/guide/components/provide-inject.md

**Comment by web-wgf** [comment]
> 
这里没有翻译

![image](https://user-images.githubusercontent.com/69149369/154437156-a6d082cb-ee4d-4f7e-bcf4-3a8c1c386e0d.png)

**Comment by veaba** [comment]
已并入
