### ISSUE TITLE
英文版里的 SFC 要保留英文缩写还是翻译成单文件组件

### ISSUE THREAD

**Issue by Jinjiang** [vuejs-translations/docs-zh-cn#940]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

译法讨论

### 问题描述

如题。我个人倾向于全部翻译成“单文件组件”，因为这是中文语境里更常见也是更好理解的译法。不知道大家怎么觉得。
目前我们的中文文档保留 SFC 和翻译成单文件组件的做法都有
谢谢

参考：
- https://github.com/search?q=repo%3Avuejs-translations%2Fdocs-zh-cn%20SFC&type=code
- https://github.com/vuejs/router/pull/2234#issuecomment-2109148296 by @GYHHAHA

**Comment by wxsms** [comment]
倾向于不翻译。SFC 是一个 vuejs 文档向读者介绍的专有名词（like HTML/DOM）。印象中原文首次出现 SFC 的重要篇章一般有解释，如：

> 在大多数启用了构建工具的 Vue 项目中，我们可以使用一种类似 HTML 格式的文件来书写 Vue 组件，它被称为单文件组件 (也被称为 *.vue 文件，英文 Single-File Components，缩写为 SFC)。

> 一个 Vue 单文件组件 (SFC)，通常使用 *.vue 作为文件扩展名，它是一种使用了类似 HTML 语法的自定义文件格式，用于定义 Vue 组件。

可见原文档已经照顾了对 SFC 概念不熟悉的阅读者体验。以及是打算将 SFC 这个专有名词介绍给用户的。

另外，术语表中也存在该词条及对应解释。因此，我觉得没有翻译的必要。

**Comment by Jinjiang** [comment]
如果仅为了向读者介绍专有名词，我更倾向于反过来：1) 全文用中文翻译，2) 同时在第一次出现的地方或其他较为明显的地方注明英文缩写

1. 阅读体验方面：英文正文使用缩写是因为缩写和全称之间有推导关系，意会的可能性更大，这也是英文阅读的惯性思维，遇到缩写就本能的反向联想全称。中文不存翻译在这个推导关系，读起来也不通顺，所以通篇英文缩写对中文阅读体验的影响远大过英文。
2. 目前有类似情况的词还有不少，但基本上底层专有词汇，或者换句话说，不是 Vue 本身创造出来的词汇的缩写才会被保留。你举的例子 HTML、DOM 都是如此。对于 Vue 文档来说，我们是假定读者对底层知识有一定熟悉度的。
3. 从大众熟悉度的角度，HTML、DOM 是我们平时中文开发者交流会选用的词汇，但是 SFC 我个人和国内开发者交流下来几乎没有直接这样叫的，包括 SFC、VOA、VCA 在内，大家的表达习惯还是单文件组件、选项式 API、组合式 API，这些习惯是经过实践检验的。从这个角度，我也不建议刻意在文档里保留这些缩写。
4. 在第一次出现的地方或其他较为明显的地方提及英文缩写，这样读者即便在特定场合遇到了这个缩写不清楚什么意思，回到中文文档站依然可以通过搜索或其他方式查阅到。这个需求和频繁阅读理解文档相比客观来看是次要的。

**Comment by Justineo** [comment]
赞同 @Jinjiang

**Comment by liulijiexian** [comment]
> 赞同 @Jinjiang

+1

**Comment by Jinjiang** [comment]
那我们就统一到翻译成“单文件组件”了，我稍后更新一下英文缩写的翻译原则
