### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by TownYouth** [vuejs-translations/docs-zh-cn#942]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

文档翻译相关

### 问题描述

在 文档/依赖注入/Prop 逐级透传问题 章节中的第一段语句——“通常情况下，当我们需要从父组件向子组件传递数据时，会使用 props。想象一下这样的结构：有一些多层级嵌套的组件，形成了一颗巨大的组件树……”，“一颗组件数”量词使用错误，应修改为“一棵组件数”

**Comment by Justineo** [comment]
感谢，欢迎提交 PR~

**Comment by Justineo** [comment]
Fixed in #943.
