### ISSUE TITLE
https://cn.vuejs.org/api/sfc-script-setup.html#defineprops-defineemits该URL地址失效

### ISSUE THREAD

**Issue by micro-carving** [vuejs-translations/docs-zh-cn#955]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

![Snipaste_2024-05-30_00-06-15](https://github.com/vuejs-translations/docs-zh-cn/assets/52859955/343433d1-6b29-41b7-8fa6-1f3a3bddc93d)
链接访问失效：https://cn.vuejs.org/api/sfc-script-setup.html#defineprops-defineemits

**Comment by KiritaniAyaka** [comment]
这边访问没问题，可能是缓存导致，强制刷新试试

**Comment by veaba** [comment]
方案见楼上。
