### ISSUE TITLE
内置组件部分页面失效

### ISSUE THREAD

**Issue by Json-Luo** [vuejs-translations/docs-zh-cn#960]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

内置组件两个页面失效了 404  英文版本可以正常访问
[Transition](https://cn.vuejs.org/guide/built-ins/transition.html)
[TransitionGroup](https://cn.vuejs.org/guide/built-ins/transition-group.html)
<img width="648" alt="image" src="https://github.com/vuejs-translations/docs-zh-cn/assets/20723791/234d95f9-0709-45c9-83f2-14207a40c779">

**Comment by veaba** [comment]
CTRL+ F5 强下。
