### ISSUE TITLE
移动端 自动获取焦点导致页面偏移

### ISSUE THREAD

**Issue by Tofu-Xx** [vuejs-translations/docs-zh-cn#967]
移动端 自动获取焦点导致页面偏移
![Screenshot_2024-06-27-18-53-27-73_40deb401b9ffe8e](https://github.com/vuejs-translations/docs-zh-cn/assets/124511155/3aad9f59-0555-4711-a5e7-076c2a2fd168)

**Comment by veaba** [comment]
由于 #1054  的 commit，banner 显示问题已被注释掉，现 close 此 issue
