### ISSUE TITLE
Higher-level \ Opinionated \ Hacky 译法讨论

### ISSUE THREAD

**Issue by MarvinXu** [vuejs-translations/docs-zh-cn#97]
### Higher-level
没有找到相关中文译法，只有类似的词汇：
- [高低端 - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E9%AB%98%E4%BD%8E%E9%9A%8E)：指命题抽象化的程度
- [高级语言 - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E9%AB%98%E7%BA%A7%E8%AF%AD%E8%A8%80)

在 [SSR 文档](https://vuejs.org/guide/scaling-up/ssr.html#higher-level-solutions) 中常用的搭配是
- higher-level solutions
- higher-level framework

感觉翻译为“高端”、“高级”都不合适，另外原译者翻译为“高阶”感觉也不合适，“高阶”一般跟“高阶函数”相关，意义完全不同，这里的含义应该是“抽象化程度更高的”。

### Opinionated
这里摘抄了一段解释：
> Opinionated Software is a software product that believes a certain way of approaching a business process is inherently better and provides software crafted around that approach. 
> 
> If a framework is opinionated, it lock or guides you into their way of doing things.

大概意思就是一个软件或框架有自己的一套偏好或者“最佳实践”，它既是一种指引也是一种约束。

本文中的例句：_Therefore, we highly recommend going with a higher-level, opinionated solution that abstracts away the complexity for you._

我暂且译为：“偏好明确的解决方案”

### Hacky
含义：badly designed \ temporary workaround

例句：*You might be able to get it working by mocking some of the globals, but it would be hacky and may interfere with the environment detection code of other libraries.*

因为 hack 这个词我们常说，所以我意译成了“这只是一种 hack 手段”

欢迎讨论

**Comment by Justineo** [comment]
- higher-level framework 感觉可以译为“上层框架”
- opinionated 感觉不太好对应中文的形容词，我觉得可以调整句子的表达方式比如：如果一个框架融入了较多的主观偏好，那么……
- hacky 不太确定，可以保留原文？

**Comment by Jinjiang** [comment]
- higher-level 在我看来不是什么术语，翻译成“更上层”之类的就可以了，其它意思接近的译法也可以
- opinionated 我觉得“个人主见”可能贴切一些
- hacky 本身是个非正式的描述，我之前会选择比较口语化的翻译，比如“偏门”、“取巧”、“讨巧”之类的，供大家参考

**Comment by MarvinXu** [comment]
感谢 @Justineo @Jinjiang  的意见，因为结合句子看可能会更实际，我重新组织了原句的翻译：

> A complete implementation would be quite complex and depends on the build toolchain you have chosen to work with. Therefore, we highly recommend going with a higher-level, opinionated solution that abstracts away the complexity for you.
>
> 一个完整的实现会非常复杂，并且取决于你选择使用的构建工具链。因此，我们强烈建议选择一种更上层、偏主观 (opinionated) 的解决方案，为你抽象掉这些复杂性。
> 
> You might be able to get it working by mocking some of the globals, but it would be hacky and may interfere with the environment detection code of other libraries.
>
> 你或许能通过模拟一些全局变量来解决，但这样做有些取巧 (hacky) 并且可能会干扰其他库的环境检测代码。

说明：“取巧”虽然不能完全解释“hacky”但在这个句子里满足语义且更通顺，加上原词注释帮助理解。

**Comment by wxsms** [comment]
### higher-level

> higher-level framework 感觉可以译为“上层框架”

赞同**上层框架**。

### opinionated framework

这里是形容框架。翻译为“个人主见”、“主观偏好”，感觉不太合适。这里如果按照意思来说，应该是在形容框架提供了有明确风格偏好的 API，即“具象”。

对应例句：If a framework is opinionated, it lock or guides you into their way of doing things.

翻译为：一个具象的框架将约束或指引你按照它的方式去工作。

### hacky 

我觉得 `is hacky` 可以翻译为“具有侵入性”：

> but it would be hacky and may interfere with the environment detection code of other libraries.

但是它具有侵入性，并且可能影响到其它库的环境检测。

**Comment by Justineo** [comment]
> 我觉得 `is hacky` 可以翻译为“具有侵入性”

侵入性对应的英文一般是 intrusive。

**Comment by wxsms** [comment]
相关 PR 我先合并了。上述术语后续讨论结果确定下来以后，我们可以再进行更新，谢谢。

**Comment by Jinjiang** [comment]
个人觉得这里的讨论也比较充分了，且这几个词不算是术语，case by case 只要合理就没有问题。不介意的话我先关掉了。后续讨论可以跟着相应的具体 PR 或讨论来进行。

谢谢
