### ISSUE TITLE
Eager (watch) 如何翻译

### ISSUE THREAD

**Issue by Jinjiang** [vuejs-translations/docs-zh-cn#98]
问题来源：https://github.com/vuejs-translations/docs-zh-cn/pull/42

相关英文段落：

> ## Eager Watchers \*
> 
> `watch` is lazy by default: the callback won't be called until the watched source has changed. But in some cases we may want the same callback logic to be run eagerly - for example, we may want to fetch some initial data, and then re-fetch the data whenever relevant state changes.
> 
> We can force a watcher's callback to be executed immediately by declaring it using an object with a `handler` function and the `immediate: true` option:
> 
> ```js
> export default {
>   // ...
>   watch: {
>     question: {
>       handler(newQuestion) {
>         // this will be run immediately on component creation.
>       },
>       // force eager callback execution
>       immediate: true
>     }
>   }
>   // ...
> }
> ```
> 
> </div>
> 
> <div class="composition-api">
> 
> ## `watchEffect()` \*\*
> 
> `watch()` is lazy: the callback won't be called until the watched source has changed. But in some cases we may want the same callback logic to be run eagerly - for example, we may want to fetch some initial data, and then re-fetch the data whenever relevant state changes. We may find ourselves doing this:
> 
> ```js
> const url = ref('https://...')
> const data = ref(null)
> 
> async function fetchData() {
>   const response = await fetch(url.value)
>   data.value = await response.json()
> }
> 
> // fetch immediately
> fetchData()
> // ...then watch for url change
> watch(url, fetchData)
> ```
> 
> This can be simplified with [`watchEffect()`](/api/reactivity-core.html#watcheffect). `watchEffect()` allows us to perform a side effect immediately while automatically tracking the effect's reactive dependencies. The above example can be rewritten as:
> 
> ```js
> watchEffect(async () => {
>   const response = await fetch(url.value)
>   data.value = await response.json()
> })
> ```
> 
> Here, the callback will run immediately. During its execution, it will also automatically track `url.value` as a dependency (similar to computed properties). Whenever `url.value` changes, the callback will be run again.
> 
> You can check out [this example](/examples/#fetching-data) with `watchEffect` and reactive data-fetching in action.

谢谢

**Comment by Matrix53** [comment]
个人认为可以视情况翻译成`即时`或`立即`。

考虑到`lazy`一词在中文中经常被翻译为`懒`，如懒加载、懒汉单例模式等，意义为`将计算任务延迟执行`。

`eager`一词中文貌似没有特别合适的词汇来表达，意义为`将计算任务即时执行`的词个人觉得没有特别合适的。

个人认为可以翻译为`即时`，`即时监听`，并且加一些注释之类的。

**Comment by Jinjiang** [comment]
我感觉即便是“即使监听”还是表意不明，因为主语还是“监听”。但其实这里的意思应该是“立即执行”。所以不仅仅是 eager 本身译法 (相比于 lazy) 的问题。

或许我们可以考虑一些非直译的手段，为这个含义重新设计一个中文描述。

**Comment by wxsms** [comment]
> we may want the same callback logic to be run eagerly

我们可能希望xxx的执行更即时

> force eager callback execution

强制执行即时回调

------

> 但其实这里的意思应该是“立即执行”

个人觉得“即时”也有一层“立即”的意思。当然，这里的本意就是“立即执行”，下面紧跟着的参数也是 `immediate`。因此如果不想纠结的话，我们也许可以给英文发个PR，将：

> force eager callback execution

修改为：

> force immediate callback execution

这样就好办了。上面的 to be run eagerly 翻译为“更加及时”，下面的就翻译为“立即执行”。

**Comment by Justineo** [comment]
F.Y.I. eager 这个词在类似属于中，中文维基百科用的是”及早“：https://zh.wikipedia.org/wiki/%E5%8F%8A%E6%97%A9%E6%B1%82%E5%80%BC

但”及早“这个词感觉似乎用于术语更合适，在各种其他上下文里不太好搭配。

“立即”可能的确更合适，但是感觉并不适合用来直接描述 watcher。

> Eager Watchers

实际上表达的是“watchers whose callback logic is run eagerly”，那么是不是可以展开一下实际的意思，比如“立即（即时）回调的监听器”，或者“回调立即执行的监听器”。

> But in some cases we may want the same callback logic to be run eagerly

基于上面的：“但在某些情况下我们可能希望回调逻辑立即执行”

**Comment by Jinjiang** [comment]
> 英文的 eager 给人感觉是描述一种行为模式而不是某个具体东西执行的时机。中文好像不太有直接对应的词，用即刻侦听感觉丢失了意思，这里形容的是回调，所以我建议还是展开一点描述清楚一点。

认同，这个正是我最早纠结的地方。但我感觉找不到完全精准的译法了，即便是英文文档里，也是做了更多解释的。

这么说回来可能还是即刻最合适了，我暂时想不到什么更好的译法。另外附加上后续的段落作为解释，或许也能接受。

> 即刻侦听
>
> `watch` 默认是懒惰的：其回调函数直到被侦听的源变化时才会被调用。但是在一些场景下，我们可能想要立即运行一次回调函数的逻辑——比如我们可能想要请求一些初始化数据，并在状态改变时重新请求这些数据。

即：
- eager -> 即刻
- eagerly -> 立即

**Comment by Justineo** [comment]
我还是倾向直接展开，比如“即时回调的监听器”。

**Comment by Jinjiang** [comment]
OK，那就这个展开的版本吧。
