### ISSUE TITLE
文档样式丢失

### ISSUE THREAD

**Issue by autel-houguoqi** [vuejs-translations/docs-zh-cn#984]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

文档样式丢失，如下：
![image](https://github.com/user-attachments/assets/f4567127-5b63-43f8-8373-fead374778a7)

**Comment by luren-h** [comment]
部分接口404，其他语言都不会

**Comment by WhySoRed** [comment]
同样，并且搜索按钮失效

**Comment by veaba** [comment]
中文站在过去几个月报告了多起 404 issue，我们判断是 Cloudflare 在国内 CDN 节点不稳定引起（抽风），对此，目前没有好办法。

参考此  Tag：https://github.com/vuejs-translations/docs-zh-cn/issues?q=is%3Aissue+is%3Aclosed

## 相关 issue：

#885 #931 #919

## 解决思路

- #886 （禁用缓存）
- 稍后再重刷、重进

**Comment by ddviper** [comment]
其他语种都没问题啊？没道理就中文有问题，如果中文的样式文件因为cdn的问题不能访问，那不能放其他语种的CDN里吗？

**Comment by ddviper** [comment]
> 其他语种都没问题啊？没道理就中文有问题，如果中文的样式文件因为cdn的问题不能访问，那不能放其他语种的CDN里吗？

-挂一个梯子就能访问了。真是离谱。

**Comment by simply-none** [comment]
换一种方式来说，可以自己搭建一个本地服务，也很快的

**Comment by zzs89117920** [comment]
![image](https://github.com/user-attachments/assets/e7f64080-091a-44e1-b091-ef1eeae80b0f)

**Comment by EnochGao** [comment]
禁用缓存并不管用

**Comment by veaba** [comment]
> ![image](https://private-user-images.githubusercontent.com/5515847/350810089-e7f64080-091a-44e1-b091-ef1eeae80b0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Mjc0NTMsIm5iZiI6MTcyMTYyNzE1MywicGF0aCI6Ii81NTE1ODQ3LzM1MDgxMDA4OS1lN2Y2NDA4MC0wOTFhLTQ0ZTEtYjA5MS1lZjFlZWFlODBiMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMDU0NTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGVhYmQ1NzU4YzhlNDQ2ZTQ0ODM1OTAwMWY2MjRkYzE1NmU5NzFhMjMxN2I0YzZjNGI2M2QyNDUyNjY3ZTgwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MULhsyht3QzjoPj500qQSaXFV_5-eALyuHH1XTxl5bc)

点击 那个 css 连接能正常吗，尝试多刷几次

**Comment by EnochGao** [comment]
![image](https://github.com/user-attachments/assets/d8f04521-bfc3-4494-bff1-c16400e6c711)

刷冒烟了，山东，并不行。但是繁体翻译站点就可以

**Comment by veaba** [comment]
仅供参考，可以发现确实 CF 不太稳。

cn.vuejs.org
![image](https://github.com/user-attachments/assets/4a57cd0e-963f-4c5f-b59a-a67bd67c97c3)

vuejs.org
![image](https://github.com/user-attachments/assets/47fea75d-4bd6-46ec-9ab2-033af6d1c603)

@yyx990803 @Jinjiang  是否考虑将 `Cloudflare` 切换为 `Netlify`

**Comment by veaba** [comment]
> ![image](https://private-user-images.githubusercontent.com/41459067/350853286-d8f04521-bfc3-4494-bff1-c16400e6c711.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Mjg2NjAsIm5iZiI6MTcyMTYyODM2MCwicGF0aCI6Ii80MTQ1OTA2Ny8zNTA4NTMyODYtZDhmMDQ1MjEtYmZjMy00NDk0LWJmZjEtYzE2NDAwZTZjNzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA2MDYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNmQ4OWQxNjE5YjBlZmY3ZGZlOTkwZWUyOWI4YzM4OTkyY2FiZTRmMTNhMzc2MGU3NTU2ODc3NWJkNTViN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4uIM7dS8WdX_L1-JjxdMTHEMoGw9TdZRbNX5t-x2PMU)
> 
> 刷冒烟了，山东，并不行。但是繁体翻译站点就可以

用这个顶一下：https://docs-zh-145taxrck-vuejs.vercel.app/ （每次发版地址都不一样）

## 入口

入口在这里：https://github.com/vuejs-translations/docs-zh-cn/deployments/Production

步骤1：
![image](https://github.com/user-attachments/assets/bef5f8f1-a363-4ea4-a43b-47431eb41cdb)

步骤2：
![image](https://github.com/user-attachments/assets/7197a234-e58d-4d47-9c66-0aada802a3d2)

**Comment by Jinjiang** [comment]
统一回复一下，首先我们确实发现主站最近出现了在国内访问不稳定的情况，对由此带来的不便深表歉意 🙏 

我们近期也在做一些相关的信息收集和调研，但没有立刻切换别的部署方式，是因为根据经验每家 CDN 都时好时坏，包括之前也跟国内的一些服务合作过，也是说没就没了。非常遗憾。

我个人建议大家暂时通过以下两个网址试试看：
- https://vue-docs-zh-cn.netlify.app/
- https://vue-docs-zh-cn.vercel.app/

如果有更加长期稳定的选择，我们都会考虑，并跟大家保持信息同步。

谢谢

**Comment by zzzzzyuzhang** [comment]
this script is not found in vue official website simplified Chinese version 
![image](https://github.com/user-attachments/assets/9ee91818-5eba-4f75-97d5-b216718840c6)

**Comment by Jinjiang** [comment]
@zzzzzyuzhang would you mind double-checking the DevTools about other resources?
![image](https://github.com/user-attachments/assets/bbe99979-1aba-4f39-87cf-b54ae6b673ec)

The resources on the screenshot are on the same server with same domain and server config. If you just can't load only one or part of them, I would suggest you force refresh (or force reload cache) to see whether it works. Usually it's just an casual incident.

If all the resources failed to load, please let me know your location. We will try to take some further investigations. At the same time, you are welcome to try another 2 backup domains:

- [vue-docs-zh-cn.netlify.app](https://vue-docs-zh-cn.netlify.app/)
- [vue-docs-zh-cn.vercel.app](https://vue-docs-zh-cn.vercel.app/)

Thanks.

**Comment by yangtianfu01** [comment]
繁体中文一点事都没有， 自有gq在此？离谱

**Comment by Ricky816845** [comment]
搜索功能不好使，风格偏好也切换不了，和英文站点搜索页不一样，有大半年了吧，啥情况？
![QQ_1723616871965](https://github.com/user-attachments/assets/fd08df9f-14e9-4523-874c-f9a3d0d18048)

**Comment by yyx990803** [comment]
> 繁体中文一点事都没有， 自有gq在此？离谱

之前 netlify 大陆直连慢，所以换到了 vercel，但后来 vercel 也不稳定，为了改善速度才加了 CloudFlare cache，而现在的文件丢失问题是 CF cache 在大陆的部分节点不稳定导致的。还真是国情导致的，其他地区 vercel / netlify 直连都没有任何问题...

**Comment by veaba** [comment]
以下为 Vuejs 官方中文站清单：

|部署厂商|备份站点|
|----|----|
|主站点|https://cn.vuejs.org/|
|Netlify|https://vue-docs-zh-cn.netlify.app/|
|Vercel | https://vue-docs-zh-cn.vercel.app/|
|CloudFlare Pages|https://cn-staging.vuejs.org/|

**如访问有问题，尝试 `Ctrl+F5` 仍然不行**，麻烦留下你的所在的区域，我们排查下

**Comment by yyx990803** [comment]
之前 app.xxxxx.js 应该是在 CF 的某个节点有缓存污染导致明明存在但一直 404，最近刚刚重新 build 了新的 hash，目前部署在 CloudFlare pages，国内测试应该没有问题了，暂时关闭这个 issue，如果有问题再看。
