### ISSUE TITLE
文档貌似丢失了

### ISSUE THREAD

**Issue by Gstonelee** [vuejs-translations/docs-zh-cn#992]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

其他

### 问题描述

vue3文档我点击左侧菜单项的模板语法显示404
![Snipaste_2024-08-14_11-29-03](https://github.com/user-attachments/assets/f8ed654c-5e67-489e-b518-9f4e18401c4b)

**Comment by veaba** [comment]
#984  在跟进。

**Comment by KiritaniAyaka** [comment]
缓存问题，试试强制刷新
